### ISSUE TITLE
[Feature Request] Add metaworld support

### ISSUE THREAD

**Issue by Guitaricet** [learnables/learn2learn#105]
Hi!
Thank you for learn2learn!

It would be great to have the support of Metaworld environments (it is pretty tricky right now and requires to change some source code). I'd be happy to help.

**Comment by seba-1511** [comment]
Hello @Guitaricet,

Thanks for the kind words! We would love to have support for Meta-World in leaarn2learn, but no one is working on it right now. I think a reasonable approach is to first have a working implementation for a single environment, and to scale that up to the 10 tasks setting following the existing MAML implementation.

If you're interested in contributing an integration of meta-world, feel free to join our slack and we can discuss details there: [slack.learn2learn.net](http://slack.learn2learn.net)

Cheers,
- Séb

**Comment by seba-1511** [comment]
Add in #144 - closing.
