### ISSUE TITLE
Is testing necessary in every epoch (MAML vision examples)?

### ISSUE THREAD

**Issue by Kostis-S-Z** [learnables/learn2learn#108]
I might be misunderstanding something completely but, in the MAML vision examples (maml_miniimagenet & maml_omniglot) the normal train/val/test split takes place but testing also happens in every epoch during training. Why is that? Isn't this the purpose of the validation set? Shouldn't testing be left just for after the training? Also, testing at every epoch slows down the training time.

**Comment by seba-1511** [comment]
That's correct, we don't need to test at every iteration and in a real-world setting don't want to do it either. This would make for an easy first PR!
