### ISSUE TITLE
About New Dataset

### ISSUE THREAD

**Issue by LifaSun** [learnables/learn2learn#124]
Dear all,

Thanks for sharing the excellent work! I saw the training datasets in the examples are from learn2learn or torchvision. If we want to try some new datasets, e.g. speech recognition dataset, could you tell me how to make it work? 

Could you give me an example? Thank you very much!

**Comment by seba-1511** [comment]
As long as it's a PyTorch `Dataset` for a classification task, you should be able to just swap the datasets.

**Comment by LifaSun** [comment]
@seba-1511 Thanks for your help! I am trying to swap the datasets, but error comes up when running "train_tasks.sample():

ValueError: Sample larger than population or is negative

In Detail:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-57-76a1c036b3fb> in <module>
----> 1 train_task = train_tasks.sample()
      2 # data, labels = train_tasks[0]
      3 # data[0]
      4 # labels[0]
      5 # train_loader

/data2/lfsun/py3-env/conda/envs/pytorch1_4/lib/python3.6/site-packages/learn2learn/data/task_dataset.py in sample(self)
    122 
    123     def __len__(self):
--> 124         if self.num_tasks == -1:
    125             # Ok to return 1, since __iter__ will run forever
    126             # and __getitem__ will always resample.

/data2/lfsun/py3-env/conda/envs/pytorch1_4/lib/python3.6/site-packages/learn2learn/data/task_dataset.py in __getitem__(self, i)
    135         task_description = self.sampled_descriptions[i]
    136         return self.get_task(task_description)
--> 137 
    138     def __iter__(self):
    139         self._task_id = 0

/data2/lfsun/py3-env/conda/envs/pytorch1_4/lib/python3.6/site-packages/learn2learn/data/task_dataset.py in sample_task_description(self)
     97         description = copy.deepcopy(self.dataset_description)
     98         if callable(self.task_transforms):
---> 99             return self.task_transforms(description)
    100         for transform in self.task_transforms:
    101             description = transform(description)

/data2/lfsun/py3-env/conda/envs/pytorch1_4/lib/python3.6/site-packages/learn2learn/data/transforms.py in __call__(self, task_description)
    174     def __call__(self, task_description):
    175         classes = list(set([self.dataset.indices_to_labels[dd.index] for dd in task_description]))
--> 176         classes = random.sample(classes, k=self.n)
    177         return [dd for dd in task_description if self.dataset.indices_to_labels[dd.index] in classes]
    178 

/data2/lfsun/py3-env/conda/envs/pytorch1_4/lib/python3.6/random.py in sample(self, population, k)
    318         n = len(population)
    319         if not 0 <= k <= n:
--> 320             raise ValueError("Sample larger than population or is negative")
    321         result = [None] * k
    322         setsize = 21        # size of a small set minus size of an empty list

ValueError: Sample larger than population or is negative

**Comment by seba-1511** [comment]
How many classes does your dataset have ? It seems like you set values for `NWays` to be larger than that.

**Comment by LifaSun** [comment]
Thanks! Let's discuss it on slack.

**Comment by LifaSun** [comment]
@seba-1511 Could you give me an invitation link on  learnables.slack.com？ My slack account is sunlifa.cuhk@gmail.com Thanks!
