### ISSUE TITLE
Clarification why in examples it is "2*shots" instead of just "shots"

### ISSUE THREAD

**Issue by Kostis-S-Z** [learnables/learn2learn#125]
(If this seems trivial, feel free to close it / delete it)

This is a probably really small detail, but I thought I share it since the library keeps growing. In the examples (e.g maml_miniimagenet.py) you can see that an algorithm is called with the following hyper-parameters `ways = 5, shots = 5`

But then during the transformation of the data to task datasets we can see that the Kshots transformation is being called like this: `KShots(train_dataset, 2*shots)`.

At first glance (and mostly for beginners in the few-shot classification field) this might look strange. Someone might ask: "Does this mean that the model actually trains with 5 or 10 samples per class?". 

The explanation is that during the adaptation phase ("inner loop" in maml terms) you need X amount of samples to adapt and another X amount of samples to evaluate the adaptation. So in the end, it does indeed train with 5 samples (as initially stated).

This is how it is intended to work, it is not a bug, I just thought I make a comment on it for future reference since I was a bit confused the first time I saw it. I am not sure if it needs to be changed... maybe we can just add a comment explaining why this function should always be called like this `KShots(train_dataset, 2*shots)` instead of this `KShots(train_dataset, shots)`.

Another obvious solution would be that KShots was called like this `KShots(train_dataset, shots)` but it actually returned 2*shots samples.

(I realize my wording is not very accurate but I hope I made myself clear... let me know if you need further clarification)

**Comment by Kostis-S-Z** [comment]
It is now mentioned in a [tutorial](https://learn2learn.net/tutorials/anil_tutorial/ANIL_tutorial/) so I am closing this.

**Comment by rg321** [comment]
Thanks @Kostis-S-Z, I was exactly looking for this explanation
