### ISSUE TITLE
Failed to establish a new connection: [WinError 10060] 

### ISSUE THREAD

**Issue by songyy5517** [learnables/learn2learn#126]
Hi,
I failed to run the news_topic_classification.py, and it shows the following error:

**_requests.exceptions.ConnectionError: HTTPSConnectionPool(host='www.dropbox.com', port=443): Max retries exceeded with url: /s/o71z7fq7mydbznc/train_sample.csv.zip?dl=1 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D15B128E08>: Failed to establish a new connection: [WinError 10060]_**

Do you know what's wrong with it?
By the way, I know the dataset has 41 catagories, is there anyhing more about the dataset?
Thanks a lot!

**Comment by seba-1511** [comment]
Hello @songyy5517,

Unfortunately this text example should be removed, as we never managed to get MAML to work well on it. It uses the deprecated `TaskGenerator` API that was removed from learn2learn in November. 

If you want to contribute an example -- even very simple -- on news classification, I'd gladly merge it. In the meantime, I think we should remove this script as it is more misleading than helpful.
