### ISSUE TITLE
Multi-GPU support?

### ISSUE THREAD

**Issue by xieshuqin** [learnables/learn2learn#128]
Thanks for the awesome work of learn2learn. 

I wonder if this package supports DataParallel Model and more general distributed training? Specifically, does MAML model support multi-gpu training?

**Comment by seba-1511** [comment]
Hello @xieshuqin,

Using `nn.DataParallel` might work if you wrap your model with it before wrapping it with `l2l.algorithms.MAML`. However, unless you have more than a few samples per class I doubt you'll see any speed-up.

On the other hand, the `MAML` wrapper should work out-of-the-box with `nn.DistributedDataParallel`. I'd recommend it, as you can effectively scale the number of workers with the number of tasks in your meta-batch.

If you ever implement the `DistributedDataParallel` approach, we'd be happy to include it as an example in the repo.
