### ISSUE TITLE
Reptile example issue

### ISSUE THREAD

**Issue by joey-wang123** [learnables/learn2learn#132]
Dear authors,

        Thank you for your fantastic projects and contributions! I currently use your code base for reptile experiment for miniimagenet. I run the script reptile_miniimagenet.py and got the following errors. 

  `      RuntimeError: Expected 4-dimensional input for 4-dimensional weight 32 3 3, but got 3-dimensional input of size [10, 84, 84] instead`

After that, I change the original code of.
  
`    data = random.sample(adaptation_data, batch_size)
     adapt_X = torch.cat([d[0].unsqueeze(0) for d in data], dim=0).to(device)
     adapt_y = torch.cat([torch.tensor(d[1]).view(-1) for d in data], dim=0).to(device)
     opt.zero_grad()
     error = loss(learner(adapt_X), adapt_y)
`

To the following, similar to the script in MAML miniimagenet:
 
`error = loss(learner(adaptation_data), adaptation_labels)`

But the performance is  worse, close to 40%, could you tell me how to get the similar results in the reptile paper? Thank you!

**Comment by seba-1511** [comment]
Hi @joey-wang123 ,

I can finally confirm that the uploaded reptile example is an older version which does not replicate published results. I'll create a PR to fix that. In the meantime, you can have a look at [this gist](https://gist.github.com/seba-1511/30e08ff2e680769dc06bc6da81cd33e7) to get an idea of what the changes will look like.

Thanks again for reporting this.

**Comment by joey-wang123** [comment]
Many thanks for your reply!

Séb Arnold <notifications@github.com> 于2020年5月15日周五 下午3:39写道：

**Comment by steremma** [comment]
Any update on this?

**Comment by seba-1511** [comment]
Thanks for the reminder @steremma! The new version is merged in #225 :)
