### ISSUE TITLE
no attribute indices_to_labels for custom dataset

### ISSUE THREAD

**Issue by anujshah1003** [learnables/learn2learn#136]
AttributeError                            Traceback (most recent call last)
<ipython-input-19-6468cc065af9> in <module>
      1 train_tasks = l2l.data.TaskDataset(tire_train,
      2                                        task_transforms=[
----> 3                                             l2l.data.transforms.NWays(tire_train, ways),
      4                                             l2l.data.transforms.KShots(tire_train, 2*shots),
      5                                             l2l.data.transforms.LoadData(tire_train),

learn2learn/data/transforms.pyx in learn2learn.data.transforms.NWays.__init__()

learn2learn/data/transforms.pyx in learn2learn.data.transforms.CythonNWays.__init__()

AttributeError: 'Tire' object has no attribute 'indices_to_labels'

**Comment by seba-1511** [comment]
`tire_train = learn2learn.data.MetaDataset(tire_train)`

**Comment by anujshah1003** [comment]
@seba-1511 Thank you , that solved the issue
