### ISSUE TITLE
Applicable to text classification ?

### ISSUE THREAD

**Issue by robinsongh381** [learnables/learn2learn#143]
On issue #96, @seba-1511  mentioned that learn2learn was not adequate for text and i was wondering if this is still true

Thanks

**Comment by seba-1511** [comment]
Hello @robinsongh381 ,

You can absolutely use learn2learn for text. My comment in #96 was that we weren't able to get good performance on that particular text dataset with MAML. On the other hand, I think @debajyotidatta only tried during the hackathon so it might work with a bit more efforts.
