### ISSUE TITLE
TaskGenerator,Sample

### ISSUE THREAD

**Issue by xhtian95** [learnables/learn2learn#145]
I have two questions. 1. Is the task generator API cancelled now? 2. How can I sample supportset and queryset from a sample task, I mean by which API?

**Comment by seba-1511** [comment]
Hello @xhtian95,

Yes, the task generator API was deprecated in early November. To sample support and query sets, you can have a look at the TaskDataset in the ProtoNet example:

https://github.com/learnables/learn2learn/blob/master/examples/vision/protonet_miniimagenet.py#L114
