### ISSUE TITLE
How to apply different transforms to adaptation and evaluation tasks

### ISSUE THREAD

**Issue by guybuk** [learnables/learn2learn#147]
Hello,
Thanks for `learn2learn`!

I'm having trouble implementing the following, and I was hoping for some guidance:

Given my dataset, `TieredImagenet`, I would like to create a meta-testing task, which is as follows:

- support set: 5-way 1-shot
    - 5 total copies of different augmentations for these original 5 images
    - Total of 25 images in support set
- query set: (same classes)-way 15 shot.
    - Total of 75 query images

This means 2 things:
1. Apply transformations to the support set that don't apply to the query set
2. Have these transformations copy only the support set but not the query set.

Right now, this is my code: 
```python
def aug_support(num_copies):
    def copy_task(task_description):
        copies = [DataDescription(desc.index) for desc in task_description for i
                  in range(num_copies)]
        return copies

    return copy_task

dataset = TieredImagenet(root='/nfs/datasets/classification/tiered',
                         mode='test', transform=train_transform,
                         target_transform=None)
dataset = MetaDataset(dataset)
nways = 5
kshots = 1
augs = 5
nqueries = 7
tasks = TaskDataset(dataset, task_transforms=[
    FusedNWaysKShots(dataset, n=nways, k=kshots + nqueries),
    RemapLabels(dataset),
    ConsecutiveLabels(dataset),
    aug_support(5),
    LoadData(dataset),
], num_tasks=600)
for batch in tasks:
    # do things...
```

This means the following:
1. Augmentations happen to both query and support (because the transform is passed to the dataset object)
2. I'm copying both support and query in `aug_support`.

Is there a way to do these things using this repo?

Thanks!

**Comment by seba-1511** [comment]
Hello @guybuk,

If I understand correctly, the simplest solution in your case would be to remove the `LoadData` transform, and instead load and augment the data directly in your `aug_support` transform.

Loading the data is [a one-liner](https://github.com/learnables/learn2learn/blob/master/learn2learn/data/transforms.pyx#L92), and once you've done your augmentation you could let the first 25 samples in your set be support and the next 75 be queries.
