### ISSUE TITLE
Visualize and plot the results

### ISSUE THREAD

**Issue by Katsumi-N** [learnables/learn2learn#148]
Thanks for great codes.
but I'm beginner and want to know how to visualize and plot the results about Ant task.

Thanks.

**Comment by seba-1511** [comment]
Hi @Katsumi-N,

There are two solutions:

1. Write a script to visualize the agent in your usual OpenAI Gym environment. [Here's some info](http://gym.openai.com/docs/#environments)
2. Use the [VisdomLogger](https://github.com/learnables/cherry/blob/master/cherry/envs/visdom_logger_wrapper.py#L39) wrapper in cherry.
