### ISSUE TITLE
ImportError: cannot import name 'DiagNormalPolicy' from 'policies' 

### ISSUE THREAD

**Issue by yt7589** [learnables/learn2learn#150]
I had this problem when run examples/rl/maml_trpo.py:
` from policies import DiagNormalPolicy
ImportError: cannot import name 'DiagNormalPolicy' from 'policies' (D:\software\anaconda3\envs\py37\lib\site-packages\policies\__init__.py)`   

How to fix this problem?

**Comment by seba-1511** [comment]
Hi @yt7589 ,

What is the command and the script you're running?

**Comment by seba-1511** [comment]
Innactive.
