### ISSUE TITLE
cannot import name 'transforms' from 'learn2learn.data'

### ISSUE THREAD

**Issue by beyondnpu** [learnables/learn2learn#156]

**Comment by joemzhao** [comment]
can you provide a minimal example showing how to reproduce this issue?

**Comment by seba-1511** [comment]
Or how you installed learn2learn on your computer.

**Comment by janbolle** [comment]
I faced the same issue. After installing it using 'pip install -e ." the issue is gone...

**Comment by seba-1511** [comment]
Hi @janbolle ,

Thanks for reporting. So simply running `pip install .` after cloning the repo wasn't enough? I think this might be caused by setup.py not compiling the Cython files without the  `-e` option. I'll look into it.

**Comment by janbolle** [comment]
Yes, was enough and after that the Cython files were there.
I assume, that @beyondnpu just cloned the repo w/o installing it?
