### ISSUE TITLE
meaning of number tasks

### ISSUE THREAD

**Issue by joey-wang123** [learnables/learn2learn#157]
Thanks a lot for your great repo, which helps my research a lot. I have one question for the example in maml omnilgot. Does num_tasks=20000 mean that  the whole task set is randomly sampled with 20000 tasks, then at each iterations, each batch is sampled from these 20000 tasks? Thank you!

**Comment by seba-1511** [comment]
Hello @joey-wang123 and thanks for the kind words,

Yes, your understanding is correct: with `num_tasks=20000`, calling `.sample()` will randomly sample one of 20k tasks.

**Comment by joey-wang123** [comment]
Thank you for your help!
