### ISSUE TITLE
New examples like iMAML and Reptile using learn2learn

### ISSUE THREAD

**Issue by AyanKumarBhunia** [learnables/learn2learn#158]
I am new to this meta-learning domain. Could you please upload example codes for iMAML and Reptile?

**Comment by seba-1511** [comment]
Hello @AyanKumarBhunia 

You can find Reptile in [this gist](https://gist.github.com/seba-1511/30e08ff2e680769dc06bc6da81cd33e7).

We don't have an implementation for iMAML yet but would welcome one from the community.
