### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by whzyf951620** [learnables/learn2learn#159]
ImportError: /home/wangheng/anaconda3/envs/learn2learn/lib/python3.6/site-packages/torchvision/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

pytorch = 1.4.0
cuda = 9.0
torchvision = 0.3.0
python = 3.6

**Comment by seba-1511** [comment]
Hello @whzyf951620 ,

How did you install learn2learn and which script are you trying to run?

**Comment by whzyf951620** [comment]
You are right, I have solve this problem, thank you!
But a new problem is yield while I want to pickle.load the MiniImageNet-Train Dataset.
'UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9f in position 2061817: invalid start byte'.
But this problem has not been yileded when I load the vaildation dataset.
