### ISSUE TITLE
Question about RL optimizer

### ISSUE THREAD

**Issue by JeremyAlain** [learnables/learn2learn#164]
I have a question about the RL/maml_dice.py example. 

Namely on line 92 it says `opt = optim.Adam(policy.parameters(), lr=meta_lr)`. What I dont understand is why you want to optimize the parameters of the policy and not the `meta_learner`defined on line 90?

If you check out maml_omniglot.py or maml_toy.py you will see that the optimizer always optimizes the `maml_object.parameters()`. 

I have checke the whole MAML class and my assumption is that basically one can write either and it is exactly the same, as the MAML object parameters are just the model parameters. However I wanted to double check if this is actually the case.

**Comment by seba-1511** [comment]
Hello @JeremyAlain ,

You are correct: with the MAML wrapper, optimizing the `policy` or the `meta_learner` parameters is completely equivalent.
