### ISSUE TITLE
Regarding differentiablity 

### ISSUE THREAD

**Issue by sudarshan1994** [learnables/learn2learn#166]
Why is this line not differentiable ?
`classifier.weight.data.add_(-lr, update)  # Not a differentiable update. See l2l.optim.DifferentiableSGD`

**Comment by seba-1511** [comment]
Hello @sudarshan1994 ,

It's not differentiable because `weight.data` does not track computations on the autograd tape. Instead, I would do: `classifier.weight = classifier.weight - lr * update`. (This is essentially what `l2l.update_module()` does under the hood.)
