### ISSUE TITLE
Checkpoints for all data sets

### ISSUE THREAD

**Issue by brando90** [learnables/learn2learn#171]
Hi,

I was wondering if checkpoints could be made available for some of the meta-learning datasets.

I am in particular interested in mini-imagenet checkpoints trained with MAML.

Though, honestly, the more checkpoints with more meta-learning algorithms the better.

**Comment by seba-1511** [comment]
Hello @brando90,

This is not our immediate priority as it's unclear which model is worth check-pointing or not. (Different papers use slightly different architecture variations). Hopefully training your own model and saving it (e.g. on Colab) should be as easy as copy-pasting the script and adding the check-pointing code.

I'll leave the issue open in case someone would like to tackle it.

**Comment by brando90** [comment]
@seba-1511 Colab allows me to run such an expensive experiment? It takes at least a day to fully train something like this...?

**Comment by seba-1511** [comment]
Yes, I carefully tested this implementation. See #280 where I give a configuration which yields decent results.

**Comment by seba-1511** [comment]
Closing since we won't provide weights for all possible configs (see [get_pretrained_backbones](https://learn2learn.net/docs/learn2learn.vision/#learn2learn.vision.models.get_pretrained_backbone) for supervised pretraining ones).
