### ISSUE TITLE
 module 'learn2learn.optim' has no attribute 'KroneckerTransform'

### ISSUE THREAD

**Issue by Evelyn-Xin** [learnables/learn2learn#173]
Hello. I have been updated learn2learn in 0.1.2 version. But  the console still reminds me " AttributeError: module 'learn2learn.optim' has no attribute 'KroneckerTransform'" How can I solve the problem? thks.

**Comment by seba-1511** [comment]
Hello @Evelyn-Xin ,

Thanks for reporting the bug, indeed we're not importing the transforms in the optim namespace. I'll fix this later today, but in the meantime you can use: `learn2learn.optim.transforms.KroneckerTransform`.

**Comment by Evelyn-Xin** [comment]
Thanks very much. And I wonder the transform class would only accept the model that defined in torch.nn or a much deeper achitecture made by self ?

**Comment by seba-1511** [comment]
The fix is merged, I'll close the issue.

The transform itself will only work with individual tensors; but you can combine it with [ParameterUpdate](http://learn2learn.net/docs/learn2learn.optim/#parameterupdate) to handle deeper architectures. (c.f. the documentation)

**Comment by Evelyn-Xin** [comment]
Thanks very much. Appreciate your work.
