### ISSUE TITLE
Accelerating learn2learn

### ISSUE THREAD

**Issue by nightlessbaron** [learnables/learn2learn#179]
Hi, 

First of all, this is a really cool library! Great work ❤️ 
I am specifically interested in accelerating meta-learners. I was previously working on accelerating a RNN optimizer based meta-learner and as there are a lot of meta-learner models, I was thinking of generalizing my work, and this library fits in the purpose perfectly. Can anyone give me a few pointers on parts of library with scope for acceleration? Also, we can think on creating a general template for accelerating a meta-learner before feeding it to the library. 🤔 🤔 
 
Does this sound feasible? Thank you! 😁 

Regards
Varad

**Comment by seba-1511** [comment]
Closing, since we've been discussing over slack.
