### ISSUE TITLE
How to adapt my custom dataset ?

### ISSUE THREAD

**Issue by wizare** [learnables/learn2learn#180]
This framework is interesting and helpful, and I want to use it work my recent work.
However, I don't know how to adapt it for my custom dataset. 
In my work, I have got the task label of each sample, that means each sample is {X, Y, T}, where X is input, Y is output label and T is task label.

The tutorial shows that I should specify the 'labels_to_indices' argument. 
But the tutorial lack the demo that how to define the 'labels_to_indices' argument so that I am confused ..

**Comment by seba-1511** [comment]
Hello @wizare ,

It seems like you want to have `Y` in your `labels_to_indices`. In this case, it should simply be `labels_to_indices[Y] = [y for (x, y, t) in mydataset if y == Y]`. (This is just a naive example, you probably want to implement more efficiently.)

**Comment by wizare** [comment]
Hi @seba-1511 , thanks for your reply.

My previous description is not exactly so that it seems you misunderstand my problem ...
I am confused that  when I want to initialize `MetaDataset` , it only can be fed with an argument `Dataset` as input, while the tutorial shows that the arguments are `dataset` and `label_to_indices` . 
So how should I do to input my defined `label_to_indices` into `MetaDataset` ?

The tutorial I used is this : [http://learn2learn.net/docs/learn2learn.data/#metadataset](url)

**Comment by seba-1511** [comment]
Thanks for the clarification @wizare ,

Indeed, it seems like this argument was removed and it makes sense to add it back. (Together with an optional `indices_to_labels` argument.)

In the meantime, I can see two solutions:

1. Create a class that inherits from `MetaDataset` and redefines `create_bookkeeping()`. (Did the current implementation fail for your case?)
2. Modify your dataset (or subclass it) such that it only returns `(x, y)` pairs and no `t`.

I hope this helps.
