### ISSUE TITLE
If i want employe the meta-rl on the new env , what should i do 

### ISSUE THREAD

**Issue by raozhongyu** [learnables/learn2learn#185]
Thanks for the great work! I'd like to konw if iwant employe the meta-rl on the new env (such as carla), what should i do

**Comment by Kostis-S-Z** [comment]
Hey @raozhongyu !

If you want to use an RL environment that is following a Gym-like process take a look at the [metaworld wrapper example](https://github.com/learnables/learn2learn/blob/master/learn2learn/gym/envs/metaworld/metaworld.py) on how to wrap your environment with [MetaEnv](https://github.com/learnables/learn2learn/blob/master/learn2learn/gym/envs/meta_env.py). I haven't tried carla before but from a quick search (example repos: [1](https://github.com/GokulNC/Setting-Up-CARLA-Reinforcement-Learning), [2](https://github.com/carla-rl-gym/carla-rl)) it seems there has been some work to make it behave similarly to Gym. 

Do you have a question about something else specifically? Or is there a part in the MetaEnv wrapper that is confusing to you?

**Comment by raozhongyu** [comment]
Thanks a lot , i will try it
