### ISSUE TITLE
Add LEO mini/tiere-ImageNet using pretrained feature map

### ISSUE THREAD

**Issue by IsakFalk** [learnables/learn2learn#200]
[LEO](https://openreview.net/pdf?id=BJgklhAcK7) introduced a feature map trained on mini-imagenet. It's fairly common to benchmark on this "dataset" where the instances are replaced by the feature mapped instances (which is hardcoded into the pickle files they provided). It would be good to provide a way to integrate this variation of mini and tiered-ImageNet into the datasets that learn2learn provides.

**Comment by seba-1511** [comment]
We don't provide feature maps, but we now have a way to extract them with pretrained backbones (it's more flexible than directly providing the features for every dataset). See: https://learn2learn.net/docs/learn2learn.vision/#learn2learn.vision.models.get_pretrained_backbone
