### ISSUE TITLE
Asynchronous vectorized environment does not work for cavia_trpo and maml_trpo.

### ISSUE THREAD

**Issue by yurunsheng1** [learnables/learn2learn#203]
Hi, first of all thank you so much for providing us such an excellent project! But I meet a problem and really need your help:

When I am running the cavia_trpo.py and maml_trpo.py, I met an error that: 

########
/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/site-packages/cherry/envs/base.py", line 56, in __getattr__
    return getattr(self.env, attr)
  File "/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/site-packages/cherry/envs/base.py", line 56, in __getattr__
    return getattr(self.env, attr)
  File "/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/site-packages/cherry/envs/base.py", line 56, in __getattr__
    return getattr(self.env, attr)
  [Previous line repeated 990 more times]
  File "/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/site-packages/cherry/envs/base.py", line 52, in __getattr__
    def __getattr__(self, attr):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydevd_bundle/pydevd_trace_dispatch_regular.py", line 392, in __call__
    is_stepping = pydev_step_cmd != -1
RecursionError: maximum recursion depth exceeded in comparison
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2073, in <module>
    main()
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 2067, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1418, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "/Applications/PyCharm.app/Contents/helpers/pydev/pydevd.py", line 1425, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/yurunsheng/Desktop/learn2learn-master/examples/rl/cavia_trpo.py", line 231, in <module>
    main()
  File "/Users/yurunsheng/Desktop/learn2learn-master/examples/rl/cavia_trpo.py", line 145, in main
    env = l2l.gym.AsyncVectorEnv([make_env for _ in range(num_workers)])
  File "/Users/yurunsheng/Desktop/learn2learn-master/learn2learn/gym/async_vec_env.py", line 25, in __init__
    super(AsyncVectorEnv, self).__init__(env_fns, queue=self.queue)
  File "/Users/yurunsheng/Desktop/learn2learn-master/learn2learn/gym/envs/subproc_vec_env.py", line 72, in __init__
    self.remotes[0].send(('get_spaces', None))
  File "/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/Users/yurunsheng/anaconda3/envs/marl/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
###########

But it run properly in maml_dice.py. 

May I ask you is there any difference between cavia_trpo.py and maml_dice.py  when implementing the asynchronous vectorized environment and how to solve this prbolem? I use the MacOS 10.13.6 with python 3.8.

Here is the place the bug appear:

<code>

class SubprocVecEnv(gym.Env):

    def __init__(self, env_factory, queue):
        self.lock = mp.Lock()
        self.remotes, self.work_remotes = zip(*[mp.Pipe() for _ in env_factory])
        self.workers = [EnvWorker(remote, env_fn, queue, self.lock)
                        for (remote, env_fn) in zip(self.work_remotes, env_factory)]
        for worker in self.workers:
            worker.daemon = True
            worker.start()
        for remote in self.work_remotes:
            remote.close()
        self.waiting = False
        self.closed = False
        self.remotes[0].send(('get_spaces', None))  #bugs here
        observation_space, action_space = self.remotes[0].recv()
        self.observation_space = observation_space
        self.action_space = action_space
</code>

I also found @yaoxunji met the similar problem in  https://github.com/learnables/learn2learn/issues/184. May our problems be similar?

Thank you so much for your attention! 

Best,
Runsheng

**Comment by yurunsheng1** [comment]
BTW, today i checked the code and found the difference is 

########
<code>

    def make_env():
        return gym.make(env_name)
</code>

Comparing with 

<code>

    def make_env():
        env = gym.make(env_name)
        env = ch.envs.ActionSpaceScaler(env)
        return env
</code>
##########

So i change the make_env() in maml_trpo.py and it seems can run normally. I found that ch.envs.ActionSpaceScaler() is just a wrapping to scale the action space. May I ask you why for the same environment particle-2D, maml_trpo.py uses ActionSpaceScaler(), while maml_dice.py doesnt?

Thank you again!
Runsheng

**Comment by seba-1511** [comment]
Hello @yurunsheng1 ,

Thanks for the bug report. As you saw in the cherry issue, it seems to only affect some specific users and I don't know what the cause might be. I'd be happy to merge a fix if you find one.

**Comment by yurunsheng1** [comment]
Hi @seba-1511 ,

I found that just commenting out (delete) the _getattr__() function in https://github.com/learnables/cherry/blob/master/cherry/envs/base.py  will solve my problems.

But I am not sure whether this brute action will cause any potential risk.

May I ask you is there any usage for the __getattr__() function?

Thank in advance!
Runsheng

**Comment by seba-1511** [comment]
Thanks for reporting @yurunsheng1 ,

It allows you to access `env.property` instead of `env.env.property` when you wrap your environment with `ActionSpaceScaler`. I guess the issue is with pickling. Which OS and Python version are you using?

**Comment by yurunsheng1** [comment]
Thank you so much for your reply! @seba-1511 

I use the OS 10.13.6 and the Python 3.8.5. 

BTW, If I set the breakpoint at the beginning of  getattr(), I will find that the attr has been assigned _getstate_. Unfortunately, there is no _getstate_  in _dict_ (line 53), so it will go to (line 56, the first Fig).  

Then  the attr = env,  since there is no env in  _dict_ (line 53), it still go to line 56, conduct the same behaviors, and loop forever (the second figure).

![image](https://user-images.githubusercontent.com/30396628/101566876-bffc5080-3a0a-11eb-87eb-049f10e0ebf9.png)

![image](https://user-images.githubusercontent.com/30396628/101567340-9abc1200-3a0b-11eb-91d4-6f231f86947d.png)

Is it connected to pickling? Could you give more details?

Thanks again!

**Comment by seba-1511** [comment]
This observation makes sense: the infinite recursion is also what threw your original error.

I think you're right and the issue might be due to pickling. Here's [a thread](https://stackoverflow.com/questions/49380224/how-to-make-classes-with-getattr-pickable) that proposes a fix, but maybe that instead of `attr not in vars(self.env)` we might have to check for `hasattr(self.env, attr)`.

**Comment by yurunsheng1** [comment]
Thank you so much for useful suggestions!

It almost solve my problems!  

I rewrite the <code>_ getattr_(self, attr) </code> as:
<pre>
def _ getattr_(self, attr):
        if attr not in vars(self):
            raise AttributeError
        if attr in self.__dict__.keys():
            return getattr(self, attr)
        else:
            return getattr(self.env, attr)
</pre>

However, it will still  <code>raise AttributeError </code>.

But when I put <code>_ getattr_(self, attr) </code> into <code>ActionSpaceScaler </code> class, it can run successfully.

May I ask you whether this function is well-written?

Will it be an alternative solver to this problem if I put the function to the <code>ActionSpaceScaler </code> class?

Plus, if I use the <code>hasattr(self.env, attr) </code> as you recommended, it still cast the maximum recursion error. 

<pre>
def _ getattr_(self, attr):
        if hasattr(self.env, attr):
            raise AttributeError
        if attr in self.__dict__.keys():
            return getattr(self, attr)
        else:
            return getattr(self.env, attr)
</pre>

**Comment by seba-1511** [comment]
I think we should try to fix this issue in `Wrapper`, so that other wrappers derived from it can also be used with multiprocessing. If you have time, could you try the following? (I'd do it myself but can't reproduce the error.)

```python
def __getattr__(self, attr):
    if attr in self.__dict__.keys():
        return getattr(self, attr)
    elif attr in vars(self.env):  # also try: elif hasattr(self.env, attr):
        return getattr(self.env, attr)
    else:
        raise AttributeError
```

**Comment by yurunsheng1** [comment]
Very sorry for late reply but I was so busy these days 😭.

I ran both of the codes you suggested but it is sad that it still meets the maximum recursion bug as shown in the Figs. 

But I still think the scheme you proposed are almost correct. Maybe there just still sth we ignore.

Just feel free to ask me to run the new code if you have any new idea. I am very willing to address the problems completely.

And also thank you again for giving me so many useful suggestions and helps!

![image](https://user-images.githubusercontent.com/30396628/102018895-238bd280-3dab-11eb-8955-9d0092aaaf8f.png)

![image](https://user-images.githubusercontent.com/30396628/102019015-c2b0ca00-3dab-11eb-8593-73133be45fdb.png)

**Comment by seba-1511** [comment]
Closing: inactive (and was resolved elsewhere?).
