### ISSUE TITLE
MAML BatchNorm Statistics

### ISSUE THREAD

**Issue by bereml** [learnables/learn2learn#207]
Hi, 

First of all, thank you for providing this library.

Reading the MAML MiniImageNet example, I noted that the learner is not changed to evaluation mode during the [evaluation phase](https://github.com/learnables/learn2learn/blob/b2b4b51c8532822a3334bc3e8c0f5b3e3b218961/examples/vision/maml_miniimagenet.py#L49) in the inner loop. I would like to know if that is correct since the BatchNorm statistics are normally  frozen during the evaluation phase of a conventional training procedure.

Thank again you!

**Comment by seba-1511** [comment]
Hello @bereml ,

Thanks for the nice words. I agree it's a weird implementation detail, but it exactly replicates the reference MAML implementation. See [this issue](https://github.com/cbfinn/maml/issues/9) for details.

**Comment by bereml** [comment]
Thank you very much @seba-1511. I will check in detail the issue you share with me and the original implementation.
