### ISSUE TITLE
RuntimeError: derivative for hardswish_backward is not implemented

### ISSUE THREAD

**Issue by ZHANZHl** [learnables/learn2learn#212]
[this is example](https://colab.research.google.com/drive/1ErhwA3cgRoHgfdFVO2AIw-l4j7636BGL?usp=sharing)

When I use l2l and hardswish , I get this 
RuntimeError: derivative for hardswish_backward is not implemented

What should I do if I want to use l2l and hardswish?

This problem also occurs when using torchmeta, but using hardswish alone does not have this problem. 
Why is this?

**Comment by ZHANZHl** [comment]
I solved the problem with this [code](https://github.com/ultralytics/yolov5/blob/6ab589583c86f265a8a226620cc1e87c1c2266f1/utils/activations.py#L15)
```python
class Hardswish(nn.Module):  # export-friendly version of nn.Hardswish()
    @staticmethod
    def forward(x):
        # return x * F.hardsigmoid(x)  # for torchscript and CoreML
        return x * F.hardtanh(x + 3, 0., 6.) / 6.  # for torchscript, CoreML and ONNX
```

**Comment by seba-1511** [comment]
Thanks @ZHANZHl , glad you were able to find a solution quickly!
