### ISSUE TITLE
Dice always cast errors in humanoid_direction and humanoid_forwardbackward environments.

### ISSUE THREAD

**Issue by yurunsheng1** [learnables/learn2learn#215]
Hi,  when I am running the maml_dice.py  in humanoid_direction & humanoid_forwardbackward environment, I always meet this problem:

>Traceback (most recent call last):
>  File "./maml_dice.py", line 151, in <module>
>    main()
>  File "./maml_dice.py", line 115, in main
>    loss = maml_a2c_loss(train_episodes, learner, baseline, gamma, tau)
>  File "./maml_dice.py", line 62, in maml_a2c_loss
 >   advantages = compute_advantages(baseline, tau, gamma, rewards,
>  File "./maml_dice.py", line 37, in compute_advantages
>    baseline.fit(states, returns)
>  File "/home/ryuah/anaconda3/envs/drml/lib/python3.8/site-packages/cherry/models/robotics.py", line 159, in fit
>    coeffs, _ = th.lstsq(b, A)
>RuntimeError: Lapack Error in gels : The 660-th diagonal element of the triangular factor of A is zero at 
 /pytorch/aten/src/TH/generic/THTensorLapack.cpp:177

Sadly, this bug has occurred many times and I am wondering whether it is possible to fix it or it is just the problem already in the original DICE algorithm  (cavia_trop and promp can run properly in humanoid environments, so i guess it might be the problem of DICE)? 

Thanks in advance!
Runsheng

**Comment by seba-1511** [comment]
Hi @yurunsheng1 and sorry for the late reply.

I suspect the problem is with the value in `returns`. Can you wrap `baseline.fit(states, returns)` as follows and copy-paste the value of the vector `returns` when it errors out?

```python
try:
    baseline.fit(states, returns)
except:
    import pdb; pdb.set_trace()
```

Also, what rewards do you get on humanoids for CAVIA-TRPO, ProMP, and MAML-DICE? Are they all successfully converging?

**Comment by seba-1511** [comment]
Inactive.
