### ISSUE TITLE
dataset splitting

### ISSUE THREAD

**Issue by ustraymond** [learnables/learn2learn#216]
in this example, the dataset is splitted into 3 sets, train, val, and test.

https://github.com/learnables/learn2learn/blob/master/examples/text/news_topic_classification.py

but in this example, mnist is not splitted.
https://github.com/learnables/learn2learn/blob/master/examples/vision/meta_mnist.py
The 0 to 9 images are separated into adaptation/evalutation sets.
for example, in the training step, sometimes, the digit 0 is in adaptation set, sometimes, it is in evaluation set.

my question is, why is the difference? which way should I follow?
thanks for advice.

**Comment by seba-1511** [comment]
Hi @ustraymond ,

The best way to split into three sets, as we do in the news classification example and in [our benchmarks](https://github.com/learnables/learn2learn/tree/master/learn2learn/vision/benchmarks). The MNIST example just illustrates some functionalities of the library.
