### ISSUE TITLE
Fail to install l2l via anaconda3 in windows

### ISSUE THREAD

**Issue by NCLHILL** [learnables/learn2learn#217]
Fail to install l2l via anaconda3 in windows, hope can fix the issue

**Comment by seba-1511** [comment]
Hello @NCLHILL,

Can you provide more information about this please? (E.g. what's the error message you get?) I don't use Windows, but in principle learn2learn should work there too. Make sure that you have a C compiler installed and that Cython works too: `pip install Cython learn2learn`.

**Comment by NCLHILL** [comment]
Hi,

 

Please check the error as follows:

 

Building wheels for collected packages: learn2learn

  Building wheel for learn2learn (setup.py) ... error

  ERROR: Command errored out with exit status 1:

   command: 'C:\Users\NCLHILL\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NCLHILL\\AppData\\Local\\Temp\\pip-install-7sbpbg2m\\learn2learn\\setup.py'"'"'; __file__='"'"'C:\\Users\\NCLHILL\\AppData\\Local\\Temp\\pip-install-7sbpbg2m\\learn2learn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\NCLHILL\AppData\Local\Temp\pip-wheel-z7ml5yot'

       cwd: C:\Users\NCLHILL\AppData\Local\Temp\pip-install-7sbpbg2m\learn2learn\

  Complete output (128 lines):

  running bdist_wheel

  running build

  running build_py

  creating build

  creating build\lib.win-amd64-3.8

  creating build\lib.win-amd64-3.8\learn2learn

  copying learn2learn\utils.py -> build\lib.win-amd64-3.8\learn2learn

  copying learn2learn\_version.py -> build\lib.win-amd64-3.8\learn2learn

  copying learn2learn\__init__.py -> build\lib.win-amd64-3.8\learn2learn

  creating build\lib.win-amd64-3.8\tests

  copying tests\__init__.py -> build\lib.win-amd64-3.8\tests

  creating build\lib.win-amd64-3.8\learn2learn\algorithms

  copying learn2learn\algorithms\base_learner.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

  copying learn2learn\algorithms\gbml.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

  copying learn2learn\algorithms\maml.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

  copying learn2learn\algorithms\meta_sgd.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

  copying learn2learn\algorithms\__init__.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

  creating build\lib.win-amd64-3.8\learn2learn\data

  copying learn2learn\data\utils.py -> build\lib.win-amd64-3.8\learn2learn\data

  copying learn2learn\data\__init__.py -> build\lib.win-amd64-3.8\learn2learn\data

  creating build\lib.win-amd64-3.8\learn2learn\gym

  copying learn2learn\gym\async_vec_env.py -> build\lib.win-amd64-3.8\learn2learn\gym

  copying learn2learn\gym\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym

  creating build\lib.win-amd64-3.8\learn2learn\nn

  copying learn2learn\nn\kroneckers.py -> build\lib.win-amd64-3.8\learn2learn\nn

  copying learn2learn\nn\misc.py -> build\lib.win-amd64-3.8\learn2learn\nn

  copying learn2learn\nn\__init__.py -> build\lib.win-amd64-3.8\learn2learn\nn

  creating build\lib.win-amd64-3.8\learn2learn\optim

  copying learn2learn\optim\learnable_optimizer.py -> build\lib.win-amd64-3.8\learn2learn\optim

  copying learn2learn\optim\parameter_update.py -> build\lib.win-amd64-3.8\learn2learn\optim

  copying learn2learn\optim\__init__.py -> build\lib.win-amd64-3.8\learn2learn\optim

  creating build\lib.win-amd64-3.8\learn2learn\text

  copying learn2learn\text\__init__.py -> build\lib.win-amd64-3.8\learn2learn\text

  creating build\lib.win-amd64-3.8\learn2learn\vision

  copying learn2learn\vision\transforms.py -> build\lib.win-amd64-3.8\learn2learn\vision

  copying learn2learn\vision\__init__.py -> build\lib.win-amd64-3.8\learn2learn\vision

  creating build\lib.win-amd64-3.8\learn2learn\gym\envs

  copying learn2learn\gym\envs\meta_env.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs

  copying learn2learn\gym\envs\subproc_vec_env.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs

  copying learn2learn\gym\envs\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs

  creating build\lib.win-amd64-3.8\learn2learn\gym\envs\metaworld

  copying learn2learn\gym\envs\metaworld\metaworld.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\metaworld

  copying learn2learn\gym\envs\metaworld\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\metaworld

  creating build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

  copying learn2learn\gym\envs\mujoco\ant_direction.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

  copying learn2learn\gym\envs\mujoco\ant_forward_backward.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

  copying learn2learn\gym\envs\mujoco\dummy_mujoco_env.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

  copying learn2learn\gym\envs\mujoco\halfcheetah_forward_backward.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

  copying learn2learn\gym\envs\mujoco\humanoid_direction.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

 copying learn2learn\gym\envs\mujoco\humanoid_forward_backward.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

  copying learn2learn\gym\envs\mujoco\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

  creating build\lib.win-amd64-3.8\learn2learn\gym\envs\particles

  copying learn2learn\gym\envs\particles\particles_2d.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\particles

  copying learn2learn\gym\envs\particles\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\particles

  creating build\lib.win-amd64-3.8\learn2learn\optim\transforms

  copying learn2learn\optim\transforms\kronecker_transform.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

  copying learn2learn\optim\transforms\metacurvature_transform.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

  copying learn2learn\optim\transforms\module_transform.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

  copying learn2learn\optim\transforms\transform_dictionary.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

  copying learn2learn\optim\transforms\__init__.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

  creating build\lib.win-amd64-3.8\learn2learn\optim\update_rules

  copying learn2learn\optim\update_rules\differentiable_sgd.py -> build\lib.win-amd64-3.8\learn2learn\optim\update_rules

  copying learn2learn\optim\update_rules\__init__.py -> build\lib.win-amd64-3.8\learn2learn\optim\update_rules

  creating build\lib.win-amd64-3.8\learn2learn\text\datasets

  copying learn2learn\text\datasets\news_classification.py -> build\lib.win-amd64-3.8\learn2learn\text\datasets

  copying learn2learn\text\datasets\__init__.py -> build\lib.win-amd64-3.8\learn2learn\text\datasets

  creating build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

  copying learn2learn\vision\benchmarks\cifarfs_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

  copying learn2learn\vision\benchmarks\fc100_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

  copying learn2learn\vision\benchmarks\mini_imagenet_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

  copying learn2learn\vision\benchmarks\omniglot_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

  copying learn2learn\vision\benchmarks\tiered_imagenet_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

  copying learn2learn\vision\benchmarks\__init__.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

  creating build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\cifarfs.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\cu_birds200.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\describable_textures.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\fc100.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\fgvc_aircraft.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\fgvc_fungi.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\full_omniglot.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\mini_imagenet.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\quickdraw.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\tiered_imagenet.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\vgg_flowers.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  copying learn2learn\vision\datasets\__init__.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

  creating build\lib.win-amd64-3.8\learn2learn\vision\models

  copying learn2learn\vision\models\cnn4.py -> build\lib.win-amd64-3.8\learn2learn\vision\models

  copying learn2learn\vision\models\resnet12.py -> build\lib.win-amd64-3.8\learn2learn\vision\models

  copying learn2learn\vision\models\__init__.py -> build\lib.win-amd64-3.8\learn2learn\vision\models

  creating build\lib.win-amd64-3.8\tests\integration

  copying tests\integration\maml_miniimagenet_test_notravis.py -> build\lib.win-amd64-3.8\tests\integration

  copying tests\integration\maml_omniglot_test.py -> build\lib.win-amd64-3.8\tests\integration

  copying tests\integration\protonets_miniimagenet_test_notravis.py -> build\lib.win-amd64-3.8\tests\integration

  copying tests\integration\__init__.py -> build\lib.win-amd64-3.8\tests\integration

  creating build\lib.win-amd64-3.8\tests\unit

  copying tests\unit\utils_test.py -> build\lib.win-amd64-3.8\tests\unit

  copying tests\unit\__init__.py -> build\lib.win-amd64-3.8\tests\unit

  creating build\lib.win-amd64-3.8\tests\unit\algorithms

  copying tests\unit\algorithms\gbml_test.py -> build\lib.win-amd64-3.8\tests\unit\algorithms

  copying tests\unit\algorithms\maml_test.py -> build\lib.win-amd64-3.8\tests\unit\algorithms

  copying tests\unit\algorithms\metasgd_test.py -> build\lib.win-amd64-3.8\tests\unit\algorithms

  copying tests\unit\algorithms\__init__.py -> build\lib.win-amd64-3.8\tests\unit\algorithms

  creating build\lib.win-amd64-3.8\tests\unit\data

  copying tests\unit\data\metadataset_test.py -> build\lib.win-amd64-3.8\tests\unit\data

  copying tests\unit\data\task_dataset_test.py -> build\lib.win-amd64-3.8\tests\unit\data

  copying tests\unit\data\transforms_test.py -> build\lib.win-amd64-3.8\tests\unit\data

  copying tests\unit\data\util_datasets.py -> build\lib.win-amd64-3.8\tests\unit\data

  copying tests\unit\data\__init__.py -> build\lib.win-amd64-3.8\tests\unit\data

  creating build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\benchmarks_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\cifarfs_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\cu_birds200_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\describable_textures_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\fc100_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\fgvc_aircraft_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\quickdraw_test_no.py -> build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\tiered_imagenet_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\vgg_flowers_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

  copying tests\unit\vision\__init__.py -> build\lib.win-amd64-3.8\tests\unit\vision

  running build_ext

  building 'learn2learn.data.meta_dataset' extension

  creating build\temp.win-amd64-3.8

  creating build\temp.win-amd64-3.8\Release

  creating build\temp.win-amd64-3.8\Release\learn2learn

  creating build\temp.win-amd64-3.8\Release\learn2learn\data

  cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\NCLHILL\anaconda3\include -IC:\Users\NCLHILL\anaconda3\include /Tclearn2learn/data/meta_dataset.c /Fobuild\temp.win-amd64-3.8\Release\learn2learn/data/meta_dataset.obj

  error: command 'cl.exe' failed: No such file or directory

  ----------------------------------------

  ERROR: Failed building wheel for learn2learn

  Running setup.py clean for learn2learn

Failed to build learn2learn

Installing collected packages: learn2learn

    Running setup.py install for learn2learn ... error

    ERROR: Command errored out with exit status 1:

     command: 'C:\Users\NCLHILL\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NCLHILL\\AppData\\Local\\Temp\\pip-install-7sbpbg2m\\learn2learn\\setup.py'"'"'; __file__='"'"'C:\\Users\\NCLHILL\\AppData\\Local\\Temp\\pip-install-7sbpbg2m\\learn2learn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\NCLHILL\AppData\Local\Temp\pip-record-5dl3sd1r\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\NCLHILL\anaconda3\Include\learn2learn'

         cwd: C:\Users\NCLHILL\AppData\Local\Temp\pip-install-7sbpbg2m\learn2learn\

    Complete output (128 lines):

    running install

    running build

    running build_py

    creating build

    creating build\lib.win-amd64-3.8

    creating build\lib.win-amd64-3.8\learn2learn

    copying learn2learn\utils.py -> build\lib.win-amd64-3.8\learn2learn

    copying learn2learn\_version.py -> build\lib.win-amd64-3.8\learn2learn

    copying learn2learn\__init__.py -> build\lib.win-amd64-3.8\learn2learn

    creating build\lib.win-amd64-3.8\tests

    copying tests\__init__.py -> build\lib.win-amd64-3.8\tests

    creating build\lib.win-amd64-3.8\learn2learn\algorithms

    copying learn2learn\algorithms\base_learner.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

    copying learn2learn\algorithms\gbml.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

    copying learn2learn\algorithms\maml.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

    copying learn2learn\algorithms\meta_sgd.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

    copying learn2learn\algorithms\__init__.py -> build\lib.win-amd64-3.8\learn2learn\algorithms

    creating build\lib.win-amd64-3.8\learn2learn\data

    copying learn2learn\data\utils.py -> build\lib.win-amd64-3.8\learn2learn\data

    copying learn2learn\data\__init__.py -> build\lib.win-amd64-3.8\learn2learn\data

    creating build\lib.win-amd64-3.8\learn2learn\gym

    copying learn2learn\gym\async_vec_env.py -> build\lib.win-amd64-3.8\learn2learn\gym

    copying learn2learn\gym\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym

    creating build\lib.win-amd64-3.8\learn2learn\nn

    copying learn2learn\nn\kroneckers.py -> build\lib.win-amd64-3.8\learn2learn\nn

    copying learn2learn\nn\misc.py -> build\lib.win-amd64-3.8\learn2learn\nn

    copying learn2learn\nn\__init__.py -> build\lib.win-amd64-3.8\learn2learn\nn

    creating build\lib.win-amd64-3.8\learn2learn\optim

    copying learn2learn\optim\learnable_optimizer.py -> build\lib.win-amd64-3.8\learn2learn\optim

    copying learn2learn\optim\parameter_update.py -> build\lib.win-amd64-3.8\learn2learn\optim

    copying learn2learn\optim\__init__.py -> build\lib.win-amd64-3.8\learn2learn\optim

    creating build\lib.win-amd64-3.8\learn2learn\text

    copying learn2learn\text\__init__.py -> build\lib.win-amd64-3.8\learn2learn\text

    creating build\lib.win-amd64-3.8\learn2learn\vision

    copying learn2learn\vision\transforms.py -> build\lib.win-amd64-3.8\learn2learn\vision

    copying learn2learn\vision\__init__.py -> build\lib.win-amd64-3.8\learn2learn\vision

    creating build\lib.win-amd64-3.8\learn2learn\gym\envs

    copying learn2learn\gym\envs\meta_env.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs

    copying learn2learn\gym\envs\subproc_vec_env.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs

    copying learn2learn\gym\envs\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs

    creating build\lib.win-amd64-3.8\learn2learn\gym\envs\metaworld

    copying learn2learn\gym\envs\metaworld\metaworld.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\metaworld

    copying learn2learn\gym\envs\metaworld\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\metaworld

    creating build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

    copying learn2learn\gym\envs\mujoco\ant_direction.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

    copying learn2learn\gym\envs\mujoco\ant_forward_backward.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

    copying learn2learn\gym\envs\mujoco\dummy_mujoco_env.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

    copying learn2learn\gym\envs\mujoco\halfcheetah_forward_backward.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

    copying learn2learn\gym\envs\mujoco\humanoid_direction.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

    copying learn2learn\gym\envs\mujoco\humanoid_forward_backward.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

    copying learn2learn\gym\envs\mujoco\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\mujoco

    creating build\lib.win-amd64-3.8\learn2learn\gym\envs\particles

    copying learn2learn\gym\envs\particles\particles_2d.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\particles

    copying learn2learn\gym\envs\particles\__init__.py -> build\lib.win-amd64-3.8\learn2learn\gym\envs\particles

    creating build\lib.win-amd64-3.8\learn2learn\optim\transforms

    copying learn2learn\optim\transforms\kronecker_transform.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

    copying learn2learn\optim\transforms\metacurvature_transform.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

    copying learn2learn\optim\transforms\module_transform.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

    copying learn2learn\optim\transforms\transform_dictionary.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

    copying learn2learn\optim\transforms\__init__.py -> build\lib.win-amd64-3.8\learn2learn\optim\transforms

    creating build\lib.win-amd64-3.8\learn2learn\optim\update_rules

    copying learn2learn\optim\update_rules\differentiable_sgd.py -> build\lib.win-amd64-3.8\learn2learn\optim\update_rules

    copying learn2learn\optim\update_rules\__init__.py -> build\lib.win-amd64-3.8\learn2learn\optim\update_rules

    creating build\lib.win-amd64-3.8\learn2learn\text\datasets

    copying learn2learn\text\datasets\news_classification.py -> build\lib.win-amd64-3.8\learn2learn\text\datasets

    copying learn2learn\text\datasets\__init__.py -> build\lib.win-amd64-3.8\learn2learn\text\datasets

    creating build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

    copying learn2learn\vision\benchmarks\cifarfs_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

    copying learn2learn\vision\benchmarks\fc100_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

    copying learn2learn\vision\benchmarks\mini_imagenet_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

    copying learn2learn\vision\benchmarks\omniglot_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

    copying learn2learn\vision\benchmarks\tiered_imagenet_benchmark.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

    copying learn2learn\vision\benchmarks\__init__.py -> build\lib.win-amd64-3.8\learn2learn\vision\benchmarks

    creating build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\cifarfs.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\cu_birds200.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\describable_textures.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\fc100.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\fgvc_aircraft.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\fgvc_fungi.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\full_omniglot.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\mini_imagenet.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\quickdraw.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\tiered_imagenet.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\vgg_flowers.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    copying learn2learn\vision\datasets\__init__.py -> build\lib.win-amd64-3.8\learn2learn\vision\datasets

    creating build\lib.win-amd64-3.8\learn2learn\vision\models

    copying learn2learn\vision\models\cnn4.py -> build\lib.win-amd64-3.8\learn2learn\vision\models

    copying learn2learn\vision\models\resnet12.py -> build\lib.win-amd64-3.8\learn2learn\vision\models

    copying learn2learn\vision\models\__init__.py -> build\lib.win-amd64-3.8\learn2learn\vision\models

    creating build\lib.win-amd64-3.8\tests\integration

    copying tests\integration\maml_miniimagenet_test_notravis.py -> build\lib.win-amd64-3.8\tests\integration

    copying tests\integration\maml_omniglot_test.py -> build\lib.win-amd64-3.8\tests\integration

    copying tests\integration\protonets_miniimagenet_test_notravis.py -> build\lib.win-amd64-3.8\tests\integration

    copying tests\integration\__init__.py -> build\lib.win-amd64-3.8\tests\integration

    creating build\lib.win-amd64-3.8\tests\unit

    copying tests\unit\utils_test.py -> build\lib.win-amd64-3.8\tests\unit

    copying tests\unit\__init__.py -> build\lib.win-amd64-3.8\tests\unit

    creating build\lib.win-amd64-3.8\tests\unit\algorithms

    copying tests\unit\algorithms\gbml_test.py -> build\lib.win-amd64-3.8\tests\unit\algorithms

    copying tests\unit\algorithms\maml_test.py -> build\lib.win-amd64-3.8\tests\unit\algorithms

    copying tests\unit\algorithms\metasgd_test.py -> build\lib.win-amd64-3.8\tests\unit\algorithms

    copying tests\unit\algorithms\__init__.py -> build\lib.win-amd64-3.8\tests\unit\algorithms

    creating build\lib.win-amd64-3.8\tests\unit\data

    copying tests\unit\data\metadataset_test.py -> build\lib.win-amd64-3.8\tests\unit\data

    copying tests\unit\data\task_dataset_test.py -> build\lib.win-amd64-3.8\tests\unit\data

    copying tests\unit\data\transforms_test.py -> build\lib.win-amd64-3.8\tests\unit\data

    copying tests\unit\data\util_datasets.py -> build\lib.win-amd64-3.8\tests\unit\data

    copying tests\unit\data\__init__.py -> build\lib.win-amd64-3.8\tests\unit\data

    creating build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\benchmarks_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\cifarfs_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\cu_birds200_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\describable_textures_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\fc100_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\fgvc_aircraft_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\quickdraw_test_no.py -> build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\tiered_imagenet_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\vgg_flowers_test_notravis.py -> build\lib.win-amd64-3.8\tests\unit\vision

    copying tests\unit\vision\__init__.py -> build\lib.win-amd64-3.8\tests\unit\vision

    running build_ext

    building 'learn2learn.data.meta_dataset' extension

    creating build\temp.win-amd64-3.8

    creating build\temp.win-amd64-3.8\Release

    creating build\temp.win-amd64-3.8\Release\learn2learn

    creating build\temp.win-amd64-3.8\Release\learn2learn\data

    cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Users\NCLHILL\anaconda3\include -IC:\Users\NCLHILL\anaconda3\include /Tclearn2learn/data/meta_dataset.c /Fobuild\temp.win-amd64-3.8\Release\learn2learn/data/meta_dataset.obj

    error: command 'cl.exe' failed: No such file or directory

    ----------------------------------------

ERROR: Command errored out with exit status 1: 'C:\Users\NCLHILL\anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\NCLHILL\\AppData\\Local\\Temp\\pip-install-7sbpbg2m\\learn2learn\\setup.py'"'"'; __file__='"'"'C:\\Users\\NCLHILL\\AppData\\Local\\Temp\\pip-install-7sbpbg2m\\learn2learn\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\NCLHILL\AppData\Local\Temp\pip-record-5dl3sd1r\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\NCLHILL\anaconda3\Include\learn2learn' Check the logs for full command output.

**Comment by seba-1511** [comment]
Thanks for the update. It seems you don't have a C compiler properly installed. Maybe this thread can help: https://stackoverflow.com/questions/41724445/python-pip-on-windows-command-cl-exe-failed

**Comment by seba-1511** [comment]
Inactive.
