### ISSUE TITLE
error when MAML on model containing LSTM layer

### ISSUE THREAD

**Issue by raymond00000** [learnables/learn2learn#218]
Hi,

I ran this RNN example, it ran fine on my machine.
https://colab.research.google.com/drive/1dpQ6h0gDmIwLF9Duqw9XMRiPHF3cD3Ce#scrollTo=wOjkzNwaQP0K

My model contains a LSTM layer and some other layers. I would like to fix weight of LSTM layer. 

so, I set the LSTM requires_grad  to false.

            for param in self.lstm.parameters():
                param.requires_grad = False

here is my MAML code:

    torch.backends.cudnn.enabled = False

    meta_model = l2l.algorithms.MAML(model, lr=0.01, allow_unused=True)
    opt = optim.Adam(meta_model.parameters(), lr=0.005)
    ...
    learner.adapt(iteration_train_error, allow_unused=True)

Then I got this error:

RuntimeError: One of the differentiated Tensors does not require grad
    self.module = maml_update(self.module, self.lr, gradients)
UnboundLocalError: local variable 'gradients' referenced before assignment

P.S
if i set      torch.backends.cudnn.enabled = True
I got this error  RuntimeError: derivative for _cudnn_rnn_backward is not implemented

P.S
if I changed this example from RNN to LSTM. 
https://colab.research.google.com/drive/1dpQ6h0gDmIwLF9Duqw9XMRiPHF3cD3Ce#scrollTo=wOjkzNwaQP0K

    model = nn.LSTMCell(10, 20)
    hx = torch.randn(3, 20)
    cx = torch.randn(3, 20)

    for _ in range(2):
          ...
           data = torch.randn(3, 10)
           pred, cx = learner(data, (hx, cx))

then I got this error.

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.

**Comment by seba-1511** [comment]
Hi @raymond00000 ,

Thanks for opening this issue and for the colabs. Could you try passing `allow_nograd=True` to the `adapt` method?

**Comment by raymond00000** [comment]
thanks for reply.

I did this. 

    torch.backends.cudnn.enabled = True
    meta_model = l2l.algorithms.MAML(model, lr=5e-4, allow_unused=True

    learner.adapt(iteration_train_error, allow_unused=True, allow_nograd=True)

then no more error, thanks!

**Comment by raymond00000** [comment]
but does this mean LSTM layer is not supported currently? thanks!

**Comment by seba-1511** [comment]
Great, glad it worked. The LSTM should work fine with MAML, but we need to use `allow_nograd` whenever some parameters don't require gradients.

**Comment by raymond00000** [comment]
this may sound weird,

If I did not freeze the lstm layer. I would have memory error, ThenI halved the batch size, I still got gpu memory full error.

**Comment by seba-1511** [comment]
It can make sense, depending on the setup: if you adapt the LSTM parameters, you'll have to store the computation graph for the fast-adaptation. Try using fewer adaptation steps, a much smaller batch size, or a smaller model.

**Comment by raymond00000** [comment]
thanks for reply. 

I got an example, many thanks if you could help me in analysis. 

if my model original batch size is 96 that fills up the whole GPU memory, 8GB. 

how can i achieve the maximal batch size under meta-learning? and what is the maximal batch size?

firstly, I use one batch to forward pass the model,

     y1_pred = learner(x1)
     train_error  = criterion(y2_pred, y1)

then I adapt one step only.

     learner.adapt(iteration_train_error, allow_unused=True, allow_nograd=True)
 
then, I use one batch (of another label) to forward pass the learner model,

        y2_pred = learner(x2)
       train_error  = criterion(y2_pred, y2)

        opt.zero_grad()
        iteration_error.backward()
        opt.step()

is above logic correct?
my trial and error result showed the batch size reduced by 3? i.e. max=32, why?

**Comment by raymond00000** [comment]
> 
> 
> Great, glad it worked. The LSTM should work fine with MAML, but we need to use `allow_nograd` whenever some parameters don't require gradients.

I am sorry.

I forgot to change the LSTM grad to be true, so actually, it did not work. 

`torch.manual_seed(1234)
model = nn.RNN(2, 1)

model = nn.LSTMCell(10, 20)
hx = torch.randn(3, 20)
cx = torch.randn(3, 20)

# If you removed the allow_unused, you get an error (when clearly, all parameters are used)
maml = l2l.algorithms.MAML(model, lr=1e-2, allow_unused=True, allow_nograd=True)
optim = torch.optim.Adam(maml.parameters(), lr=0.1)

for i in range(20):
    optim.zero_grad()
    learner = maml.clone()


    # Short adaptation since all tasks are the same
    for _ in range(2):
        data = torch.normal(torch.zeros((30, 500, 2)))
        #learner.module._apply(lambda x: x)
        #pred, hidden = learner(data)

        data = torch.randn(3, 10)
        pred, cx = learner(data, (hx, cx))
        print(pred.shape)

        loss = criterion(10*pred, data.sum(dim=-1, keepdim=True))
        learner.adapt(loss, allow_unused=True, allow_nograd=True)

    data = torch.normal(torch.zeros((30, 500, 2)))
    data = torch.randn(3, 10)
    pred, _ = learner(data)

    loss = criterion(10*pred, data.sum(dim=-1, keepdim=True))
    loss.backward()
    optim.step()`

so, the result of above code, is actually, this error. 

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling backward the first time.
