### ISSUE TITLE
KroneckerLinear shape mismatch for 1-dimensional input

### ISSUE THREAD

**Issue by timweiland** [learnables/learn2learn#220]
Hey, thanks for this cool project!
I tried to run the example for `learn2learn.nn.KroneckerLinear` in the documentation:

```
m, n = 2, 3
x = torch.randn(6)
kronecker = KroneckerLinear(n, m)
y = kronecker(x)
y.shape
```
Unfortunately, Line 4 spits out the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tweiland/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tweiland/miniconda3/lib/python3.8/site-packages/learn2learn/nn/kroneckers.py", line 86, in forward
    x = kronecker_addmm(left, right, x, self.bias)
  File "/home/tweiland/miniconda3/lib/python3.8/site-packages/learn2learn/nn/kroneckers.py", line 12, in kronecker_addmm
    res = mat1 @ mat3 @ mat2
RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 6x1)
```
If I turn the input vector into a matrix of appropriate size first (`X = x.reshape(x.size(0) // n, n).t()`), this error does not occur and after vectorizing the output matrix (`kronecker(X).t().flatten()`), I get the correct result. Using this approach for the `if len(x.shape) == 1` branch in the implementation should fix the problem.

**Comment by seba-1511** [comment]
Hello @timweiland ,

Thanks for the nice words!

Correct, `KroneckerLinear` assumes that the input is already of shape (m, n) -- or (b, m, n) for batch size b. We expect the user to reshape before calling `forward` so as to avoid weird behaviors in the edge cases when m = 1 or n = 1. 

Your suggestion is good, and with some careful checks it should work. Would you like to give it a shot?

**Comment by timweiland** [comment]
Sure, I would like to! I'll give it a go later today.
