### ISSUE TITLE
Support for Metadatasets

### ISSUE THREAD

**Issue by mayug** [learnables/learn2learn#231]
It would be great it we have support for meta datasets. Several new research works focus on this benchmark. Do you think this would be added anytime soon?

https://github.com/google-research/meta-dataset

**Comment by seba-1511** [comment]
Hello @mayug,

We're actively adding the datasets of Meta-Dataset to learn2learn. You can already find some of them implemented in the library (e.g. Omniglot, Flowers, Aircraft, Textures, Birds, Quickdraw). For more information, check [this documentation page.](http://learn2learn.net/docs/learn2learn.vision/#learn2learnvisiondatasets) Currently missing:

- [ ] Traffic Signs
- [ ] MSCOCO
- [ ] ImageNet

I plan to get to them eventually but would also be happy to accept contributions from the community.

**Comment by Fly-dream12** [comment]
Where is the implementation of the class MetaDataset, TaskDataset, i cannot find it. @seba-1511

**Comment by seba-1511** [comment]
They are dfined here: https://github.com/learnables/learn2learn/tree/master/learn2learn/data

**Comment by Fly-dream12** [comment]
Is there any .py file? The .pyx file is not understandable.



在 2021-06-17 23:07:48，"Séb Arnold" ***@***.***> 写道：

They are dfined here: https://github.com/learnables/learn2learn/tree/master/learn2learn/data

**Comment by seba-1511** [comment]
No, they are written in Cython.
