### ISSUE TITLE
MAML example

### ISSUE THREAD

**Issue by raymond00000** [learnables/learn2learn#232]
in this example, it used MAML
https://github.com/learnables/learn2learn/blob/master/examples/vision/meta_mnist.py

in this example, it also used MAML but with first_order=False.
it did one more thing .

       # Average the accumulated gradients and optimize
       p.grad.data.mul_(1.0 / meta_batch_size)

https://github.com/learnables/learn2learn/blob/master/examples/vision/maml_omniglot.py

so, my question is, when will we have to do this step? 

       p.grad.data.mul_(1.0 / meta_batch_size)

thanks for advice.

**Comment by seba-1511** [comment]
Hello @raymond00000 ,

Sorry for the delay: that step is required to average the gradients for all tasks in a batch size. Alternatively, you can manually rescale your learning rate, which is what we did in the meta_mnist example. I recommend keeping the averaging line for simplicity.

Hope this helps!

**Comment by chris-tkinter** [comment]
Hi, I think in the original paper of MAML it uses the accumulated gradients directly instead of averaging.
![image](https://user-images.githubusercontent.com/86935669/124837994-c9b34b80-df3a-11eb-96b0-dc7b645b5f31.png)
I am wondering if there is an empirical advantage of averaging?
Thanks!

**Comment by seba-1511** [comment]
No advantage, you can just multiply the learning rate by the number of tasks in your mini-batch.
