### ISSUE TITLE
Does learn2learn support 30xx GPUs?

### ISSUE THREAD

**Issue by gsygsygsy123** [learnables/learn2learn#233]
Dear Sir/Madam,
I found that if I try MAML APIs on 3080, the speed will be slower than running on 2080 (about 10 times). I think it's very strange. Would you like to help me to figure it out?

**Comment by gsygsygsy123** [comment]
Correction: about 10 times --> 17 times.
Snapshot of runtime:
On 2080:
![image](https://user-images.githubusercontent.com/22917058/111524939-ff6bd300-8797-11eb-85f2-c172fc13770f.png)

On 3080:
![image](https://user-images.githubusercontent.com/22917058/111525000-101c4900-8798-11eb-8c6b-39557badf7df.png)


**More details:** My code clip can be summarised as :
`
learner = model.clone()
loss1 = torch.nn.MSE(learner(x), y)
learner.adapt(loss1)

loss2 = torch.nn.MSE(model(x), y)
loss2.backward()
`
I found that most of the time was spent on the `loss2.backward` step.

**Comment by gsygsygsy123** [comment]
@seba-1511 @vfdev-5 @debajyotidatta @janbolle

**Comment by gsygsygsy123** [comment]
Updates:
If I comment `learner.adapt(loss1)`, code will be fine...

**Comment by gsygsygsy123** [comment]
It seems that the reason is I use `self.register_buffer` in model.py. But I don't why...

**Comment by gsygsygsy123** [comment]
It seems inactivate. Closed.

**Comment by seba-1511** [comment]
Hello @gsygsygsy123 ,

Apologies for the delay, my open source work has taken a seat back during this pandemic.

That's an interesting issue, and I'd like to get to the bottom of it but I don't have access to a 3080 GPU. Could you paste the script you're using for those benchmarks (or better link to a colab)?

Also, what is the output if you run the following on the 2080 vs the 3080?:

~~~python
import time
import torch

Your script here . . .

optimizer.zero_grad()
torch.cuda.synchronize()
tic = time.time()
for _ in range(100):
    learner = model.clone()
torch.cuda.synchronize()
toc = time.time()
print('Time to clone:', toc - tic)

torch.cuda.synchronize()
tic = time.time()
for _ in range(10):
    loss1 = torch.nn.MSE(learner(x), y)
    learner.adapt(loss1)
torch.cuda.synchronize()
toc = time.time()
print('Time to adapt:', toc - tic)

torch.cuda.synchronize()
tic = time.time()
loss2 = torch.nn.MSE(learner(x), y)
loss2.backward()
torch.cuda.synchronize()
toc = time.time()
print('Time to backward:', toc - tic)
~~~

Thanks in advance for your help.

**Comment by gsygsygsy123** [comment]
Hi @seba-1511, please accept my deepest thanks!
Here is a slim script to reproduce the error. 
The following code snippet will report `CUDA out-of-memory`. 
```
for _ in range(10):
    loss1 = criterion(learner(x), y)
    learner.adapt(loss1)
```

Detailed error log is :
```
Traceback (most recent call last):
  File "/home/xxx/.conda/envs/xxx/lib/python3.6/site-packages/learn2learn/algorithms/maml.py", line 163, in adapt
    allow_unused=allow_unused)
  File "/home/xxx/.conda/envs/xxx/lib/python3.6/site-packages/torch/autograd/__init__.py", line 225, in grad
    inputs, allow_unused, accumulate_grad=False)
RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 9.78 GiB total capacity; 8.04 GiB already allocated; 4.31 MiB free; 8.11 GiB reserved in total by PyTorch)
learn2learn: Maybe try with allow_nograd=True and/or allow_unused=True ?
Traceback (most recent call last):
  File "test_gpu_github.py", line 29, in <module>
    learner.adapt(loss1)
  File "/home/xxx.conda/envs/xxx/lib/python3.6/site-packages/learn2learn/algorithms/maml.py", line 169, in adapt
    self.module = maml_update(self.module, self.lr, gradients)
UnboundLocalError: local variable 'gradients' referenced before assignment
```

As a result, I revise the provided benchmark code. The revised code is:
```
import time
import torch
import learn2learn as l2l
import torchvision.models.resnet as resnet

device = torch.device('cuda')
model = resnet.resnet50(pretrained=True)
model = l2l.algorithms.MAML(model, lr=0.001, first_order=False).to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.00001)

x = torch.randn(4,3,256,256).to(device)
y = torch.randn(4,1000).to(device)
criterion = torch.nn.MSELoss().to(device)


optimizer.zero_grad()
torch.cuda.synchronize()
tic = time.time()
for _ in range(100):
    learner = model.clone()
torch.cuda.synchronize()
toc = time.time()
print('Time to clone:', toc - tic)

torch.cuda.synchronize()
tic = time.time()
for _ in range(5):
    loss1 = criterion(learner(x), y)
    learner.adapt(loss1)
torch.cuda.synchronize()
toc = time.time()
print('Time to adapt:', toc - tic)

torch.cuda.synchronize()
tic = time.time()
loss2 = criterion(learner(x), y)
loss2.backward()
torch.cuda.synchronize()
toc = time.time()
print('Time to backward:', toc - tic)
```

Results on the 3080 are:
```
Time to clone: 0.40610408782958984
Time to adapt: 3.1171834468841553
Time to backward: 67.11630177497864
```
Results on the 2080 are:
```
Time to clone: 0.7698397636413574
Time to adapt: 1.8553147315979004
Time to backward: 3.3792717456817627
```

**Comment by gsygsygsy123** [comment]
I did some ablation experiments, which may bring some hints.
1. I comment `loss2.backward()` or `learner.adapt(loss1)`. Running time is similar. That is, If we only execute a single loop (without outer loop or inner loop), there is no difference between 3080 or 2080.
2. If I comment the Line 272-Line 281, runtime is also similar. The corresponding output on the 3080 is:
```
Time to clone: 0.5113298892974854
Time to adapt: 2.9373481273651123
Time to backward: 0.03151512145996094
```

**Comment by gsygsygsy123** [comment]
BTW, I also wonder why we need recursively update, as mentioned in this [issue](https://github.com/learnables/learn2learn/issues/74). I have read your reply, but I still misunderstood. What would happen if I don't use `maml_update` to recursively update submodules?

**Comment by gsygsygsy123** [comment]
If you need a 3080 to do some tests, I can try to provide a card for you. (I should get my supervisor's admit first.)

**Comment by V0XNIHILI** [comment]
I have a similar problem. This example code (https://github.com/learnables/learn2learn/blob/master/examples/vision/maml_omniglot.py) runs at 1 iteration every 23 seconds on an RTX A6000 (Ampere architecture, same as 30xx GPUs).

**Comment by aritroCoder** [comment]
> Hi @seba-1511, please accept my deepest thanks! The following code snippet will report `CUDA out-of-memory`.
> 
> ```
> for _ in range(10):
>     loss1 = criterion(learner(x), y)
>     learner.adapt(loss1)
> ```
> 
> Detailed error log is :
> 
> ```
> Traceback (most recent call last):
>   File "/home/xxx/.conda/envs/xxx/lib/python3.6/site-packages/learn2learn/algorithms/maml.py", line 163, in adapt
>     allow_unused=allow_unused)
>   File "/home/xxx/.conda/envs/xxx/lib/python3.6/site-packages/torch/autograd/__init__.py", line 225, in grad
>     inputs, allow_unused, accumulate_grad=False)
> RuntimeError: CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 9.78 GiB total capacity; 8.04 GiB already allocated; 4.31 MiB free; 8.11 GiB reserved in total by PyTorch)
> learn2learn: Maybe try with allow_nograd=True and/or allow_unused=True ?
> Traceback (most recent call last):
>   File "test_gpu_github.py", line 29, in <module>
>     learner.adapt(loss1)
>   File "/home/xxx.conda/envs/xxx/lib/python3.6/site-packages/learn2learn/algorithms/maml.py", line 169, in adapt
>     self.module = maml_update(self.module, self.lr, gradients)
> UnboundLocalError: local variable 'gradients' referenced before assignment
> ```
> 
> As a result, I revise the provided benchmark code. The revised code is:
> 
> ```
> import time
> import torch
> import learn2learn as l2l
> import torchvision.models.resnet as resnet
> 
> device = torch.device('cuda')
> model = resnet.resnet50(pretrained=True)
> model = l2l.algorithms.MAML(model, lr=0.001, first_order=False).to(device)
> optimizer = torch.optim.Adam(model.parameters(), lr=0.00001)
> 
> x = torch.randn(4,3,256,256).to(device)
> y = torch.randn(4,1000).to(device)
> criterion = torch.nn.MSELoss().to(device)
> 
> 
> optimizer.zero_grad()
> torch.cuda.synchronize()
> tic = time.time()
> for _ in range(100):
>     learner = model.clone()
> torch.cuda.synchronize()
> toc = time.time()
> print('Time to clone:', toc - tic)
> 
> torch.cuda.synchronize()
> tic = time.time()
> for _ in range(5):
>     loss1 = criterion(learner(x), y)
>     learner.adapt(loss1)
> torch.cuda.synchronize()
> toc = time.time()
> print('Time to adapt:', toc - tic)
> 
> torch.cuda.synchronize()
> tic = time.time()
> loss2 = criterion(learner(x), y)
> loss2.backward()
> torch.cuda.synchronize()
> toc = time.time()
> print('Time to backward:', toc - tic)
> ```
> 
> Results on the 3080 are:
> 
> ```
> Time to clone: 0.40610408782958984
> Time to adapt: 3.1171834468841553
> Time to backward: 67.11630177497864
> ```
> 
> Results on the 2080 are:
> 
> ```
> Time to clone: 0.7698397636413574
> Time to adapt: 1.8553147315979004
> Time to backward: 3.3792717456817627
> ```

Hi @gsygsy96 what is the reason of the error `CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 9.78 GiB total capacity; 8.04 GiB already allocated; 4.31 MiB free; 8.11 GiB reserved in total by PyTorch)`, and `UnboundLocalError: local variable 'gradients' referenced before assignment`? what are the minimum changes we need to make to fix it?
