### ISSUE TITLE
Not supporting multi-labeled Dataset?

### ISSUE THREAD

**Issue by zrajabi** [learnables/learn2learn#237]
I have a multilabeled dataset, and wanted to load data into MetaDataset but I get the following error:
dataset = l2l.data.MetaDataset(train_dataset)
learn2learn/data/meta_dataset.pyx in learn2learn.data.meta_dataset.MetaDataset.__init__()
learn2learn/data/meta_dataset.pyx in learn2learn.data.meta_dataset.MetaDataset.create_bookkeeping()
ValueError: Requires scalar labels. 
only one element tensors can be converted to Python scalars

It seems multilabel target labels are not supported and only scalar values are accepted. Could you please help me figure it out?
Thanks

**Comment by seba-1511** [comment]
Hello @zrajabi ,

Correct, MetaDataset currently doesn't support multi-label data. I'm currently working on it but don't have an estimate for when it'll be ready.

Meanwhile, you have (at least) two work-arounds, depending on how you want to use the multi-labels: 

1. Map every combination of multiple labels to a single label and recover the multiple labels once you've sample the task.
2. Duplicate every data sample for every label it has. So if sample x has labels (1, 3, 5) you'd now have 3 samples (x, 1), (x, 3), (x, 5).

**Comment by zrajabi** [comment]
Hi @seba-1511 ,
I really appreciate you for the work-around suggestions, I will try the second way and in case of facing a problem, will let you know.
