### ISSUE TITLE
FileNotFoundError：[Error 2] No such file or directory

### ISSUE THREAD

**Issue by zhang1hongliang** [learnables/learn2learn#238]
@seba-1511, @Kostis-S-Z , when I  run 'python examples/vision/protonet_miniimagenet.py', it occurs this error 'FileNotFoundError：[Error 2] No such file or directory: '/root/data/mini-imagenet-cache-train.pkl' ' though I hvae finished running 'pip install learn2learn', how can I resolve this problem?

**Comment by seba-1511** [comment]
Hello @zhang1hongliang ,

Have you set `download=True` when instantiating mini-ImageNet?

**Comment by zhang1hongliang** [comment]
Hi Arnold,


Thank you for your replying, I have set download=True, but it reported FileNotFoundError: [Error 


2] No such file or directory: '/test/learn2learn-master/data/mini-imagenet-cache-train.pkl', my 


root path is '/test/learn2learn-master', I need your help to solve this issue.


Look forward to your response.
 
Best regards,
Hongliang Zhang


On 4/25/2021 01:07，Séb ***@***.***> wrote：

Hello @zhang1hongliang ,

Have you set download=True when instantiating mini-ImageNet?

**Comment by zhang1hongliang** [comment]
@seba-1511, Thank you for your replying, I have set download=True, but it reported FileNotFoundError: [Error 2] No such file or directory: '/test/learn2learn-master/data/mini-imagenet-cache-train.pkl', my root path is '/test/learn2learn-master', I need your help to solve this issue.

**Comment by seba-1511** [comment]
Try to remove the `data/` folder and run the script again, sometimes downloading from Google drive fails.

**Comment by zhang1hongliang** [comment]
Hi Arnold,


Thank you for your replying,  it helps me a lot.  For some reasons, 


I can not download the mini_imagenet dataset from the google drive. Can I  copy the images and labels csv files into ./data then use the dataset to train model?


 If it works how can I set in the framework to make the framework run with the local dataset?


Look forward to your response.
 
Best regards,


Hongliang Zhang
| |
张宏亮
|
|
温州大学计算机与人工智能学院医学数据挖掘和计算智能研究组
***@***.***
|
签名由网易邮箱大师定制
On 4/25/2021 ***@***.***> wrote：
Hi Arnold,


Thank you for your replying, I have set download=True, but it reported FileNotFoundError: [Error 


2] No such file or directory: '/test/learn2learn-master/data/mini-imagenet-cache-train.pkl', my 


root path is '/test/learn2learn-master', I need your help to solve this issue.


Look forward to your response.
 
Best regards,
Hongliang Zhang


On 4/25/2021 01:07，Séb ***@***.***> wrote：

Hello @zhang1hongliang ,

Have you set download=True when instantiating mini-ImageNet?

**Comment by seba-1511** [comment]
You can change the path in the `root` argument of the `MiniImageNet` class. Were you able to resolve your issue?
