### ISSUE TITLE
TaskDataset sampling from UnionDataset

### ISSUE THREAD

**Issue by gosiqueira** [learnables/learn2learn#241]
Is there a way to ensure that sampling from `TaskDataset` will always select samples from the same original dataset before passing them to `UnionDataset`?

**Comment by seba-1511** [comment]
Hi @gosiqueira,

Do you mean that samples only come from a single source dataset? If so, you could simply wrap the original dataset with TaskDataset and sample directly from it.

I'm not sure this answers the question. Maybe a short snippet (pseudocode) would be helpful.

**Comment by gosiqueira** [comment]
No, I mean that I have multiple datasets that I want to join using `UnionDataset`. But, when I sample a task, this task contains only instances from a single original source. Is that possible or should I create multiple `TaskDatasets` and iterate over them?

I'm sorry to not provide any code snippet, I'm not really sure to implement such a feature.

**Comment by seba-1511** [comment]
OK, I understand better now. There are 2 ways:

1. Like you suggested, create `n` TaskDatasets and sample a task from one of them, chosen at random.
2. You could use UnionMetaDatasets and have a single TaskDataset, but you'd need to write a custom TaskTransform that chooses which MetaDataset to sample the labels from.

If you go with 2. I'd be happy to merge the transform into learn2learn and can provide a bit of guidance.

**Comment by gosiqueira** [comment]
I'll start using the first implementation for fast experimentation.
But, I do want to try the second option, specially after this merge proposal.
Next feel days I'll start it and it would be really valuable your guidance.
