### ISSUE TITLE
Working with pytorch lightning

### ISSUE THREAD

**Issue by chris-tkinter** [learnables/learn2learn#242]
Hi, thanks for your package! It really makes my life a lot easier on trying to apply meta learning on various tasks.

I have a question, how exactly to integrate this library with pytorch-lightning? I noticed a previous issue #240, but the example in the `vision/lightning`, as you mentioned, only works for lightning version `1.0.2`. 

Currently I am trying to convert [this](https://github.com/learnables/learn2learn/blob/master/examples/vision/maml_omniglot.py) simple MAML script into lightning, and [this](https://gist.github.com/chris-tkinter/74bfe9ff1237b9a938bb8345f410a23a) is what I tried so far. 

However i had this following error
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

Notice that I changed ` learner.adapt(train_error)` tp ` learner.adapt(train_error, allow_unused=True, allow_nograd=True)` since otherwise I would have this error 
```
UnboundLocalError: local variable 'gradients' referenced before assignment
```
But I am not sure if this is a correct way to fix it.

My library version is 
```
torch                  1.8.1
pytorch-lightning      1.3.8
learn2learn            0.1.5
```

I am wondering how can it be done to bypass this error? Thanks! Have a nice day!

**Comment by chris-tkinter** [comment]
Also, have you tried working with deepspeed with this library?

**Comment by seba-1511** [comment]
Apologies for the delayed reply. I have not tried DeepSpeed yet.

We're currently rewriting the lightning wrappers, because they broke for lighting>1.0.2. Could you try that version?

**Comment by c3duan** [comment]
Hi @seba-1511 , I am trying to use the learn2learn PyTorch Lightning wrappers in my project as well. Do you have an estimated timeline on when the lightning wrappers will be working for lightning>1.0.2 (for my specific use case, lightning=1.2.0+)? I am impressed by learn2learn's simple and easy-to-use API, and I am looking forward to seeing its integration with Pytorch Lightning!

**Comment by seba-1511** [comment]
Hello @c3duan,

No, we don't have a timeline and It'll likely take several weeks before we have an implementation to test. Feel free to join our slack if you'd like to help -- as far as I understand the algorithm implementations should work and only the `EpisodicBatcher` requires work.

**Comment by seba-1511** [comment]
@c3duan we've merged it recently, you can see the documentation here: https://lightning-flash.readthedocs.io/en/latest/integrations/learn2learn.html
