### ISSUE TITLE
How many meta-rl algorithms are available?

### ISSUE THREAD

**Issue by tianyma** [learnables/learn2learn#246]
Hi there, thank you for your excellent work, I wonder how many meta-rl algorithms are available now in `learn2learn`?

**Comment by seba-1511** [comment]
Right now I think we support: MAML (VPG & TRPO), CAVIA, Meta-SGD, & ProMP. I'd like to add more (eg, RL^2, PEARL) so PR are very welcome. (Check [the examples](https://github.com/learnables/learn2learn/tree/master/examples/rl) for implementations.)
