### ISSUE TITLE
Recovering original labels 

### ISSUE THREAD

**Issue by Amrou7** [learnables/learn2learn#247]
Hi. I'm using ProNet for training few-shot classification problem. My dataset consists of several products. The labels are their names. The question is: how to recover the original labels during inference for visualization purposes? I mention that after RemapLabels transform, labels are now int values and I can't access to the original string label after inference. 

To be more clear, let's suppose that I have 30 product in my test dataset. I fixed test-way=2, so we will test on 2 products chosen randomly if I understand well. The label after inference will be either 0 or 1. How can I know what 0 and 1 refer to, among the 30 products of my test dataset?

**Comment by seba-1511** [comment]
Could you apply the `RemapLabels` and `LoadData` transforms after you've sampled the task? That way you could directly work with the task description.

Another solution is to write your own task transform that tracks the true labels after they've been remapped.
