### ISSUE TITLE
what do the wrappers do on action?

### ISSUE THREAD

**Issue by tianyma** [learnables/learn2learn#248]
Hi, I cannot figure out what do the wrappers do on the action. I am currently testing `maml_trpo` on `particle-2d-navigation`, I found each time the environment step function gets an action of a list with the same number, why? How can I get the whole action list?

**Comment by seba-1511** [comment]
Can you post a snippet of the wrappers you are using? I'm also not sure what you mean by "the whole action list". The MAML-TRPO example only uses ActionSpace scaler.
