### ISSUE TITLE
Example using custom dataset

### ISSUE THREAD

**Issue by danperazzo** [learnables/learn2learn#254]
Hello everyone, thanks for releaing this wonderfull framework! I have been trying to use this framework for a project, however, I could not understand how I could adapt my custom dataset to the metadataset format. Is there any example about how to do this?

**Comment by seba-1511** [comment]
Hi @danperazzo thanks for the nice words.

If it's a classification dataset, this is very simple and you can refer to the MNIST example [here](https://github.com/learnables/learn2learn/blob/master/examples/vision/meta_mnist.py). Essentially, the dataset needs to return a (sample, label) pair and then you can just wrap it with `l2l.data.MetaDataset`. Hope this helps!

**Comment by danperazzo** [comment]
hello @seba-1511, thanks! I have been trying to use learn2learn on a problem, does your team plan on supporting this functionality in the future? And are there any examples of codes using l2l in thins setting?

**Comment by seba-1511** [comment]
For supervised learning, you could reuse `l2l.data.Taskset` but might need to adapt `l2l.data.MetaDataset` to your specific task (eg, for regression or time series). What are the tasks you're working with?

**Comment by Pathi-rao** [comment]
> hello @seba-1511, thanks! I have been trying to use learn2learn on a problem, does your team plan on supporting this functionality in the future? And are there any examples of codes using l2l in thins setting?

Hey @danperazzo, were you able to adapt the framework to your custom dataset? If so, could you please share it or point to some resources as I am also working on a custom dataset of my own and trying to figure things out. Thanks in advance.

**Comment by danperazzo** [comment]
Hello @Pathi-rao, actually I did not use the `l2l.data.MetaDataset`, I just used the standard dataet loader on my problem and it seems to work just fine.

**Comment by Waterkin** [comment]
Is there any example for maml on a time series dataset?

**Comment by Pathi-rao** [comment]
> Is there any example for maml on a time series dataset?

@Waterkin Maybe [this](https://arxiv.org/abs/2108.02842) paper could help you.

**Comment by seba-1511** [comment]
This tutorial should guide you step-by-step to build your own taskset: https://learn2learn.net/tutorials/task_transform_tutorial/transform_tutorial/
