### ISSUE TITLE
MAML++

### ISSUE THREAD

**Issue by mahdiabdollahpour** [learnables/learn2learn#261]
Hi 
Thank you for the great library and examples. it would be awesome if you could integrate MAML++ (ICLR 2019).

@inproceedings{
antoniou2018how,
title={How to train your {MAML}},
author={Antreas Antoniou and Harrison Edwards and Amos Storkey},
booktitle={International Conference on Learning Representations},
year={2019},
url={https://openreview.net/forum?id=HJGven05Y7},
}
![image](https://user-images.githubusercontent.com/27064237/133428859-f775ee97-d33b-4fe4-a45b-9e2bcd6cc0fd.png)

**Comment by DubiousCactus** [comment]
Hi! I'd be happy to submit a PR for MAML++, but most modifications to MAML proposed by this paper are done in the outer training loop. @seba-1511 any ideas on how I could wrap the outer loop logic while keeping the modular aspect of learn2learn? It does not seem really feasible as one module, so maybe it should be implemented as several helper functions and wrappers?

**Comment by seba-1511** [comment]
Hi @DubiousCactus,

Thanks, a MAML++ implementation would be great. As a first step, what about having the re-implementation in its own file (like we did for [Reptile](https://github.com/learnables/learn2learn/blob/master/examples/vision/reptile_miniimagenet.py))? Then we can merge individual components into the main library, if we think they can be useful to other implementations.

Also, thanks for PR #244. I'll try to review it ASAP.

**Comment by DubiousCactus** [comment]
Hi @seba-1511,
Sure I'll try to work on that over the weekend! And thanks for reviewing my PR.

**Comment by kzhang2** [comment]
Hey,
Is MAML++ still being worked on?

**Comment by DubiousCactus** [comment]
Hey @kzhang2,
I'm sorry I've been very busy lately and couldn't submit a PR yet... I have some pieces of MAML implemented with learn2learn, but I need to assemble everything together for a PR. I hope I can do this very soon!
