### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'output_size'

### ISSUE THREAD

**Issue by invokerpicker** [learnables/learn2learn#264]
get this error when running protonet_miniimagenet.py
the l2l version is 0.1.6

**Comment by seba-1511** [comment]
Thanks for spotting it @invokerpicker. In older versions of learn2learn the `output_size` argument of ConvBase was unused, so we removed it in 0.1.6. Removing the argument in l.32 should fix it: https://github.com/learnables/learn2learn/blob/master/examples/vision/protonet_miniimagenet.py#L32
