### ISSUE TITLE
MAML inner optimizer more flexible?

### ISSUE THREAD

**Issue by pietrolesci** [learnables/learn2learn#268]
https://github.com/learnables/learn2learn/blob/e0705a22953f06e609f7e2c4157bcab3bb2ed53b/learn2learn/algorithms/maml.py#L46

Is there a way to make the inner optimization steps more complex allowing the user to choose the inner optimizer? For example, using Adam or second order methods in the inner optimization.

**Comment by nightlessbaron** [comment]
I am also curious about this.
Most of the papers in the literature resort to simple SGD update rules.
Is it because making use of complex update rules might result in overfitting?
If that's the case, can't we overcome it using regularization?
