### ISSUE TITLE
Import segfault

### ISSUE THREAD

**Issue by ZhaofengWu** [learnables/learn2learn#282]
```
Python 3.9.7 (default, Sep 16 2021, 13:09:58) 
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import torch
>>> import learn2learn
[1]    1727048 segmentation fault (core dumped)  python
```
numpy and torch import fine, but I'm getting a segfault when importing learn2learn. Any idea why this might be happening?

**Comment by seba-1511** [comment]
How did you install learn2learn? If cloning the repo, did you run `pip install -e .` and do you have cython installed?

**Comment by ZhaofengWu** [comment]
I installed via pip -- I assume it automatically takes care of cython etc.?

**Comment by seba-1511** [comment]
Yes, it should. Do you have a c compiler installed? Try: `pip install cython` before `pip install learn2learn` just in case.

**Comment by ZhaofengWu** [comment]
Oh, it magically works now. Sorry I don't remember what I did. I'll close this for now.
