### ISSUE TITLE
First-order MetaSGD

### ISSUE THREAD

**Issue by ZhaofengWu** [learnables/learn2learn#287]
The current codebase allows a first-order MetaSGD. What does that mean? As I understand, according to this line from the [MetaSGD paper](https://arxiv.org/pdf/1707.09835.pdf), Algorithm 1
![image](https://user-images.githubusercontent.com/11954789/142956887-92e71238-6f42-484f-ba70-76af515ab594.png)
if you don't take the gradient w.r.t. the inner loop operations (aka first-order), you don't get a gradient w.r.t. alpha. So does a first-order MetaSGD just degenerate to FOMAML?

**Comment by seba-1511** [comment]
Yes. First-order meta-SGD is mostly useful for test-time, where the computation graph doesn't need to be kept in memory.

**Comment by ZhaofengWu** [comment]
Actually, I just realized that it might make sense for training-time as well: e.g. for the inner loop update `\theta <- \theta - \alpha \nabla L`, one can still take the derivative w.r.t `\alpha` only, without calculating second-order derivatives w.r.t. the parameters. Can you help confirm if this is right?

**Comment by ZhaofengWu** [comment]
Hi @seba-1511 do you mind helping confirm this? Thank you!

**Comment by seba-1511** [comment]
Yes, the learning rates get adapted.
