### ISSUE TITLE
Error loading MiniImagenet with `learn2learn==0.1.6`

### ISSUE THREAD

**Issue by ethanwharris** [learnables/learn2learn#291]
Hi :smiley:
Running the following code on `learn2learn==0.1.6`:
```
train_dataset = l2l.vision.datasets.MiniImagenet(root="data", mode="train", download=True)
val_dataset = l2l.vision.datasets.MiniImagenet(root="data", mode="validation", download=True)
```

Gives this error:
```
_pickle.UnpicklingError: invalid load key, '<'.
```

It looks like the data `pkl`s on drop box / google drive have been updated but are no longer compatible with `0.1.6`

**Comment by seba-1511** [comment]
Try to delete the archive and re-download it -- it happens when Google Drive blocks download requests for a file.
