### ISSUE TITLE
Reptile deepcopy

### ISSUE THREAD

**Issue by ZhaofengWu** [learnables/learn2learn#293]
The reptile example uses `copy.deecopy` to clone the module.
https://github.com/learnables/learn2learn/blob/676859ed85afd1662aa9aed5ad08892a3afe7adb/examples/vision/reptile_miniimagenet.py#L121

Would leran2learn's `clone_module` function do the job?
https://github.com/learnables/learn2learn/blob/676859ed85afd1662aa9aed5ad08892a3afe7adb/learn2learn/utils/__init__.py#L53

The former doesn't quite work for my use case, where my module has some auxiliary properties that are not copy-able, but those are not needed for training.

**Comment by seba-1511** [comment]
You can interchange them in this case but deepcopy should be slightly more efficient computation and memory-wise.

**Comment by ZhaofengWu** [comment]
Ok, thanks! Is there something manual I could do that is more efficient by ignoring those non-copyable properties irrelevant to training?

Another question: in this example the optimizer is re-created every step with the state dict reloaded. Is this to accommodate meta-validation? https://github.com/learnables/learn2learn/blob/676859ed85afd1662aa9aed5ad08892a3afe7adb/examples/vision/reptile_miniimagenet.py#L145

If I don't do meta-validation, can I instead maintain a single optimizer and not worry about the state dict?

**Comment by seba-1511** [comment]
No problem, glad it helped.

Yes, you could write your own `clone_module` that only clones the tensors you'd need for fast adaptation.

No, even without meta-validation you'd still need to instantiate a new optimizer that references the parameters of the learner (and share the state_dict across learners).

**Comment by ZhaofengWu** [comment]
> Yes, you could write your own `clone_module` that only clones the tensors you'd need for fast adaptation.

Sorry I think I wasn't clear. I do adapt all parameters during fast adaptation, but my model object is attached with some properties (e.g., data-related stuff, or metrics; i.e., pytorch-lightning style, if you're familiar with it) that cannot be copied (e.g., generators). In that case, would `clone_module` still have inefficiency?

> No, even without meta-validation you'd still need to instantiate a new optimizer that references the parameters of the learner (and share the state_dict across learners).

Ah, ok, that makes a lot of sense. Thank you!

**Comment by seba-1511** [comment]
No, clone_module shouldn't be inefficient in your case. I think your fix for the ValueError should work; another is to use `learner = l2l.detach_module(l2l.clone_module(model))`.

**Comment by ZhaofengWu** [comment]
Great, thanks a lot!
