### ISSUE TITLE
Derivative for cudnn_grid_sampler_backward is not implemented. 

### ISSUE THREAD

**Issue by ChaerinMin** [learnables/learn2learn#297]
Hi,

It seems that learn2learn does not support torch.nn.functional.grid_sample()'s derivative. If my understanding was right, are there any ways to readily deal with this problem or do you know any alternatives for grid_sample()? 
I appreciate that you have released such a wonderful implementation of meta-learning and find this greatly helpful for me. 

Thank you again. I am looking forward to listening from you.

**Comment by ChaerinMin** [comment]
I have found another way to cope with this issue. 
罗堃铭's strategy was useful. 
https://github.com/coolbeam/UPFlow_pytorch.git

**Comment by zslzx** [comment]
> I have found another way to cope with this issue. 罗堃铭's strategy was useful. https://github.com/coolbeam/UPFlow_pytorch.git

hi, 
I find that 罗's code also contains grid_sample(), how to avoid that? could you introduce your solution in detail? 
Thanks a lot.

**Comment by zslzx** [comment]
Solved. I have found a reimplementation of grid_sample() that works.

**Comment by Ayiing** [comment]
hi, may I ask how to avoid grid_sample? I also meet the same problems,

**Comment by Ayiing** [comment]
> Solved. I have found a reimplementation of grid_sample() that works.

hi, may I ask how to avoid grid_sample? I also meet the same problems,
