### ISSUE TITLE
can this learn2learn tools using in sequence-to-sequence task?

### ISSUE THREAD

**Issue by lavine-lmu** [learnables/learn2learn#299]
Hi, Thanks for sharing this awesome tools. I am doing seq2seq task now, but do not know how to construct the dataset, can anyone using this to do the seq2seq task before?

**Comment by seba-1511** [comment]
Hi @lavine-lmu and thanks for the nice words,

learn2learn can work for seq2seq tasks. Setting up your dataset is going to be task-specific, and it'll likely require some custom [task transforms](https://github.com/learnables/learn2learn/blob/master/learn2learn/data/transforms.pyx).

I'll close this issue but feel free to join our slack to ask for help regarding transforms.
