### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by xuliwalker** [learnables/learn2learn#300]
Hi, thanks for your great work! I am trying to use the l2l.optim.LearnableOptimizer to learn the learning rates, but I encountered an error in the second batch training:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

After I checked the source code, I found that l2l.optim.LearnableOptimizer updates the model parameters **_in-place_**, so I wonder whether this implementation is related to the error above. Thanks for your help!

**Comment by seba-1511** [comment]
Hi @xuliwalker and thanks for the nice words,

Could you post a short script to reproduce your issue? On Colab would be ideal. Could you also confirm that the [MNIST hypergrad](https://github.com/learnables/learn2learn/blob/master/examples/optimization/hypergrad_mnist.py) example runs for you?

**Comment by xuliwalker** [comment]
Thanks for the reply! Sure, I will clean my code, add some explanation comments and post it later, since the logic of my meta-learning idea is a little bit complicated, which combines MAML and Meta-descent. I was trying to run the MNIST hypergrad example, but I encountered the following error:

Traceback (most recent call last):
  File "examples/optimization/hypergrad_mnist.py", line 23, in <module>
    import learn2learn as l2l
  File "/opt/tiger/QAHOI/learn2learn/learn2learn/__init__.py", line 5, in <module>
    from . import data
  File "/opt/tiger/QAHOI/learn2learn/learn2learn/data/__init__.py", line 7, in <module>
    from . import transforms
ImportError: cannot import name 'transforms' from 'learn2learn.data'

Could you help check this issue? Thanks!

**Comment by xuliwalker** [comment]
Hi, this is the colab link of my code snippets. (https://colab.research.google.com/drive/1zm_jHUn3EkItCmpBxZLTpr2ueJr9MfgE?usp=sharing). 
Any questions about the code logic, leave me a message immediately. Thanks for your help!

**Comment by xuliwalker** [comment]
Thanks for your reply. Regarding my colab, in fact, I tried to skip the last two steps and only run the first two steps, which removes the load_state_dict operation and is simply the combination of maml and LearnableOptimizer. But as I mentioned above,  I encountered the following error in the second batch training:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [256]] is at version 2; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

Could you help check this issue? Thanks!

**Comment by mburges-cvl** [comment]
Have you found the problem? I have the same issue..

**Comment by seba-1511** [comment]
Closing: inactive.

Note that this error is quite generic, and it typically stems from non-standard computation graphs (as @xuliwalker was attempting). In this case, my advice is to skip the `LearnableOptimizer` and directly implement the update with `l2l.optim.ParameterUpdate` (similar to how it was [done in KFO](https://github.com/learnables/learn2learn/blob/master/examples/vision/anilkfo_cifarfs.py)).
