### ISSUE TITLE
how to custom time series dataset for maml?

### ISSUE THREAD

**Issue by Waterkin** [learnables/learn2learn#313]
Hello,
Thanks for the developer for learn2learn, it provides a easy-to-use python package for researchers.
But I don't quite understand how to use maml on my time series dataset, as image dataset is totally different from time series, is there any guide for this. I can only see there's image and text examples for maml.

**Comment by seba-1511** [comment]
Hi @Waterkin,

For time series you could use the MAML wrapper like we do for classification. You'll likely have to write your own training code, since it'll be dataset-dependent. Feel free to join our slack, people might be able to help.
