### ISSUE TITLE
Meta-learning for text generation?

### ISSUE THREAD

**Issue by jacklxc** [learnables/learn2learn#326]
Does learn2learn support seq2seq models, such as BART, provided by Transformers library?

**Comment by jkang1640** [comment]
I've got the same question..

**Comment by seba-1511** [comment]
Hello @jacklxc and @jkang1640,

We recently added support for parameter-efficient finetuning (see [the examples](https://github.com/learnables/learn2learn/tree/master/examples/text)). If you're specifically asking for MAML + BART, we theoretically support them (or any nn.Module) but it would likely require too much memory for training.

Hope this helps, I'm closing the issue and we can re-open if necessary.
