### ISSUE TITLE
Typo/minor issue in clone_module function

### ISSUE THREAD

**Issue by KrikunovEV** [learnables/learn2learn#329]
Hi everyone!
Probably I found a minor issue, just a typo. I don't think it breaks anything.

In the following row, there should be ```memo[buff_ptr] = cloned```, isn't it?
https://github.com/learnables/learn2learn/blob/36ac4fb8f91fec291becb4757720a82c72c550b8/learn2learn/utils/__init__.py#L139

**Comment by seba-1511** [comment]
Hi @KrikunovEV ,

Thanks for sorting this, I think you’re right. Do you want to submit a PR to fix it?
