### ISSUE TITLE
Getting label names from mini-imagenet n-way, k-shot classes

### ISSUE THREAD

**Issue by brando90** [learnables/learn2learn#332]
Hi,

I wanted to see the actual image classes (ideally as strings) e.g. cat dog etc for mini-imagenet tasks. Is it possible to do it? How does one do it?

**Comment by peiswang** [comment]
Hi, @brando90 
I also want to get the actual class names. Have you figured out how to do that? Thanks!

**Comment by peiswang** [comment]
Hi  @brando90 
Thanks for your reply. It seems that comment out the 'RemapLabels' function in transforms can return the original labels. Thanks!
https://github.com/learnables/learn2learn/blob/0b9d3a3d540646307ca5debf8ad9c79ffe975e1c/learn2learn/vision/benchmarks/mini_imagenet_benchmark.py#L91

**Comment by seba-1511** [comment]
You'd need to implement your own benchmarks to get the class names for mini-ImageNet. For tiered-ImageNet, you can look at the class_names.txt and synsets.txt to get those back.
