### ISSUE TITLE
cicular import

### ISSUE THREAD

**Issue by Chris-G-X** [learnables/learn2learn#344]
cicular import?????????why

**Comment by Chris-G-X** [comment]
cannot import name 'transforms' from partially initialized module 'learn2learn.data' (most likely due to a circular import) why?

**Comment by seba-1511** [comment]
Are you installing with `pip install learn2learn`? If not, the most likely reason is that you’re missing cython: `pip install cython`.

**Comment by swaggyP9527** [comment]
running the (maml_omniglot.py)and then:
ImportError: cannot import name 'transforms' from partially initialized module 'learn2learn.data' (most likely due to a circular import)

**Comment by seba-1511** [comment]
Did you try installing cython first?

**Comment by swaggyP9527** [comment]
I had install cython first and then install learn2learn
But why?



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "learnables/learn2learn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月2日(星期五) 晚上10:19
***@***.***&gt;;
抄送:&nbsp;"Just a ***@***.******@***.***&gt;;
主题:&nbsp;Re: [learnables/learn2learn] cicular import (Issue #344)





 
Did you try installing cython first?

**Comment by swaggyP9527** [comment]
now，i can run the maml_omniglot.py.
But,Why are training results so&nbsp;unsteadiness



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "learnables/learn2learn"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月2日(星期五) 晚上10:19
***@***.***&gt;;
抄送:&nbsp;"Just a ***@***.******@***.***&gt;;
主题:&nbsp;Re: [learnables/learn2learn] cicular import (Issue #344)





 
Did you try installing cython first?
