### ISSUE TITLE
LightningPrototypicalNetworks example fails

### ISSUE THREAD

**Issue by arshamkhodajoo** [learnables/learn2learn#346]
Hi there, why this examples is not working? why cross_entropy fails?

```python
import learn2learn as l2l
import pytorch_lightning as pl

tasksets = l2l.vision.benchmarks.get_tasksets('omniglot', root="D:/datasets/omniglot/")
features = l2l.vision.models.OmniglotCNN()
protonet = LightningPrototypicalNetworks(features)
episodic_data = EpisodicBatcher(tasksets.train, tasksets.validation, tasksets.test)
trainer = pl.Trainer()
trainer.fit(protonet, episodic_data)
```

cell ouput:

```
in Trainer._call_and_handle_interrupt(self, trainer_fn, *args, **kwargs)
    648         return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
    649     else:
--> 650         return trainer_fn(*args, **kwargs)
    651 # TODO(awaelchli): Unify both exceptions below, where `KeyboardError` doesn't re-raise
    652 except KeyboardInterrupt as exception:
...
   3012 if size_average is not None or reduce is not None:
   3013     reduction = _Reduction.legacy_get_string(size_average, reduce)
-> 3014 return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)

IndexError: Target 1 is out of bounds.
```

**Comment by arshamkhodajoo** [comment]
@seba-1511 Hi
sorry for direct mention but I still have struggle getting lightning module to work

**Comment by seba-1511** [comment]
Hello @arshamkhodajoo,

Could you put this in a colab? A priori this should work, but it looks like either the support or query targets have too large indices.

**Comment by arshamkhodajoo** [comment]
colab link: https://colab.research.google.com/drive/15nJFuO0c2f_bGQvrG0XT14ZjaPD6-RSW?usp=sharing

## Note
I had to copy/paste code for `EpisodicBatcher` because of this:
![image](https://user-images.githubusercontent.com/105818828/185227428-dd56dabf-9fed-4ead-9efb-1bf5fd606d00.png)

turns out this line throws error because `pl.callbacks.ProgressBar` is not valid anymore:
https://github.com/learnables/learn2learn/blob/f099ddc9ce0c10cff901ecb1acee2838d171272e/learn2learn/utils/lightning.py#L70
