### ISSUE TITLE
HalfCheetahForwardBackwardEnv can't output done

### ISSUE THREAD

**Issue by seolhokim** [learnables/learn2learn#349]
Hi, thank you for your contribution.

https://github.com/learnables/learn2learn/blob/6b741028f0812ba73da58acf7206d93654dde97a/learn2learn/gym/envs/mujoco/halfcheetah_forward_backward.py#L89

I fixed it by adding max_step_length parameter.

thanks.

**Comment by seolhokim** [comment]
also it makes memory leaking

**Comment by seba-1511** [comment]
Hello @seolhokim,

Thanks for the question. We define the max number of episode steps when[ registering the env](https://github.com/learnables/learn2learn/blob/master/learn2learn/gym/envs/__init__.py). This works as expected when calling `gym.make`. If instead you want to directly instantiate the env, you could use gym's [TimeLimit wrapper](https://github.com/openai/gym/blob/master/gym/wrappers/time_limit.py).

**Comment by seolhokim** [comment]
However, when printing by adding 'self.step_num = 0' in `Half Cheetah Forward Backward Env`, and adding +1 for each step, it was beyond that limit.

**Comment by seolhokim** [comment]
I used like this. Am i wrong?
```
    def make_env():
        env = HalfCheetahForwardBackwardEnv()
        env = ch.envs.ActionSpaceScaler(env)
        return env

    env = l2l.gym.AsyncVectorEnv([make_env for _ in range(num_workers)])

    env.seed(seed)
    env.set_task(env.sample_tasks(1)[0])
    env = ch.envs.Torch(env)
```

**Comment by seba-1511** [comment]
Yes, you need to use either `gym.make('HalfCheetahForwardBackward-v1')` or wrap your env with TimeLimit.

**Comment by seolhokim** [comment]
Wow thanks it solves my problem. but it is not the source of memory leaking. I will check it out.
