### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by swaggyP9527** [learnables/learn2learn#352]
running the (maml_omniglot.py)and then:
ImportError: cannot import name 'transforms' from partially initialized module 'learn2learn.data' (most likely due to a circular import)### #344

**Comment by swaggyP9527** [comment]
why?

**Comment by seba-1511** [comment]
Try pip install cython before installing learn2learn.

**Comment by swaggyP9527** [comment]
> Try pip install cython before installing learn2learn.

I still get the same result

**Comment by seba-1511** [comment]
Is it on windows? We don't support windows for now.

**Comment by woithook** [comment]
> We don't support windows for now.

Hi, I would like to ask if you have any plans to support learn2learn on windows?

**Comment by seba-1511** [comment]
No plans for now. I'm sure it should work but the installation requires a C compiler and I don't know the easiest way to enforce this requirement on Windows.
