### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by cruise-tgu** [learnables/learn2learn#359]
When I run hypergrad_mnist it shows error:
ImportError: cannot import name 'transforms' from partially initialized module 'learn2learn.data'

**Comment by cruise-tgu** [comment]
![image](https://user-images.githubusercontent.com/106368798/194273858-3f8a5cda-b137-4e82-975c-80f8c8803904.png)

**Comment by cruise-tgu** [comment]
![image](https://user-images.githubusercontent.com/106368798/194274006-6a4d4c3b-f571-42d1-b48c-dee1715b8b73.png)

**Comment by seba-1511** [comment]
How did you install learn2learn and on which OS?

**Comment by cruise-tgu** [comment]
I use pip install learn2learn  and my my os windows 11

**Comment by cruise-tgu** [comment]
> a

I use pip install learn2learn and my os is windows 11

**Comment by cruise-tgu** [comment]
> a

I use pip install learn2learn and my os is windows 11

**Comment by cruise-tgu** [comment]
> How did you install learn2learn and on which OS?

I use pip install learn2learn and my os is windows 11

**Comment by cruise-tgu** [comment]
> How did you install learn2learn and on which OS?
Could you help me to solve the problem

**Comment by seba-1511** [comment]
Sorry, there’s no guarantee that learn2learn works on Windows.

**Comment by cruise-tgu** [comment]
> Sorry, there’s no guarantee that learn2learn works on Windows.

so,what os should I choose ,linux or Macos?

**Comment by seba-1511** [comment]
Both are tested and work well.
