### ISSUE TITLE
How do I get the original Lake or Ravi et al split for onmiglot?

### ISSUE THREAD

**Issue by brando90** [learnables/learn2learn#362]
I'd like to get the same splits of omniglot so that my experiments (or future papers, experiments) don't depend on the seed i personally I use and have the same image class.

Does l2l give an option for this out of the box?

related: 

- the user the choice of classes splitting as was done in Ravi and Larochelle, 2017. http://learn2learn.net/docs/learn2learn.vision/#learn2learn.vision.datasets.full_omniglot.FullOmniglot
- https://github.com/learnables/learn2learn/issues/361

**Comment by seba-1511** [comment]
Hello @brando90, the best way is probably to ask the authors directly.
