### ISSUE TITLE
update_module has no return value，but 'module._modules[module_key] = update_module()'

### ISSUE THREAD

**Issue by fankaisheng** [learnables/learn2learn#364]
https://github.com/learnables/learn2learn/blob/master/learn2learn/utils/__init__.py
in line 239 function 'update_module' , it has no return value, but in line 308:

for module_key in module._modules:
        module._modules[module_key] = update_module(
            module._modules[module_key],
            updates=None,
            memo=memo,
        )
This will eventually cause the model defined by nn.Sequential to become none per layer

**Comment by seba-1511** [comment]
I'm not sure I understand: `update_module` returns the updated module on line 320, right?
