### ISSUE TITLE
How can I bring my own data set into MAML to create my own task set？

### ISSUE THREAD

**Issue by qiaolikui** [learnables/learn2learn#365]
I have ten groups of fault data. I want to use 1DCNN-MAML for classification. How can I put my data into l2l.data.MetaDatase? I don't know how to create my own tasks using l2l.data.TaskDataset.
This is my dataset and it is a very simple dataset. I look forward to your reply
https://drive.google.com/drive/folders/1kzBVuEEKiTq5CsjGvd9DM-EPSB25zHtw?usp=share_link

**Comment by seba-1511** [comment]
See this tutorial: http://learn2learn.net/tutorials/task_transform_tutorial/transform_tutorial/

**Comment by qiaolikui** [comment]
Thank you very much for your answer, I will try to make my dataset.
