### ISSUE TITLE
Cuda out of Memory with function adapt

### ISSUE THREAD

**Issue by Yi-Owl** [learnables/learn2learn#393]
The method of adapt in MAML will continously occupied the memory, thus result in Cuda out of Memory error with too many adapt using.
![allocate](https://user-images.githubusercontent.com/89310620/232395300-cc15c210-c65a-4f17-91be-9df6ff86acc0.png)
I've printed the memory allocated after every times cuda memory changing.
How to solve the problem if I want to adapt with more adapt steps and more data ?

**Comment by seba-1511** [comment]
Hello @Yi-Owl,

There's no solution if you want to back-propagate through the adaptation steps.

If you don't need to back-propagate, setting `first_order=True` in `adapt()` should do it. See [the docs](https://learn2learn.net/docs/learn2learn.algorithms/#learn2learn.algorithms.maml.MAML.adapt).
