### ISSUE TITLE
pip install not working

### ISSUE THREAD

**Issue by Shafin008** [learnables/learn2learn#409]
Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      error in qpth setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)
          numpy>=1<2
               ~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Shafin008** [comment]
Every time I want to pip install learn2learn this error msg shows.

**Comment by seba-1511** [comment]
Hello @Shafin008,

Could you try again now? I've just cut a new release which makes qpth optional. This should fix the installation issues.

**Comment by artths** [comment]
Just tried and I have the same issue. 
Python 3.11, Windows 11.
