### ISSUE TITLE
pip install pqth problem

### ISSUE THREAD

**Issue by CorleoneJW** [learnables/learn2learn#414]
Hi,
I just met a problem when I tried to use the pip install learn2learn and the problem was about the package pqth.
![image](https://github.com/learnables/learn2learn/assets/48402711/4e8f972e-093a-45ef-a507-bf9e7c58c38d)
I have solved this issue and here is the solution:
You can download the package provided below and unzip to pip install this package (cd to the root directory with setup.py and run pip install .).
[qpth-0.0.15.zip](https://github.com/learnables/learn2learn/files/12158742/qpth-0.0.15.zip)

**Comment by seba-1511** [comment]
Hello @CorleoneJW and @DragonDescentZerotsu,

I think this issue is better asked to the qpth maintainers since I've removed qpth from the main dependencies of learn2learn. Thanks for providing a temporary solution meanwhile, seems like it'll be useful to many people.

**Comment by artths** [comment]
pip install learn2learn
Still tries to install qpth and gives the same error.
