### ISSUE TITLE
Add Contribution and Ownership Information to README

### ISSUE THREAD

**Issue by ian-bunner** [learnables/learn2learn#60]
l2l is a young library with great potential. To accelerate it's growth we need a strong community of users who are willing to positively contribute. With that in mind, we should create a section detailing how l2l users can contribute. Ideally this section would cover both the mechanics of contributing and what contributions we are most looking for.

Additionally, we should add a section listing the code owners.

**Comment by seba-1511** [comment]
Done, in the form of the citation information.
