### ISSUE TITLE
mnist test results using default parameters: Loss : 1.609 Acc : 0.200

### ISSUE THREAD

**Issue by aGiant** [learnables/learn2learn#85]
I tested the mnist example with default parameters:

**https://github.com/learnables/learn2learn/blob/master/examples/vision/meta_mnist.py**

But got result:

**Loss : 1.609 Acc : 0.200: 100%|██████████| 1000/1000 [1:05:54<00:00,  3.89s/it]**

Does this result fit the expectation of the learn2learn design?

**Comment by praateekmahajan** [comment]
That's interesting. Can you please ensure you have the most up to date version of learn2learn? And confirm that you didn't modify learn2learn if you happened to have built it locally?

```python
import learn2learn as l2l
print(l2l.__version__)
``` 

I just created a new environment and installed `learn2learn` and did a fresh clone of the `examples/vision/meta_mnist.py` file on my local and ran `python meta_mnist.py` without any arguments and looks like I got

`Loss : 0.179 Acc : 0.956:   6%|████▋                                                                          | 60/1000 [02:42<42:33,  2.72s/it]`

If you see, we also have an integration test [(tests/integration/meta_mnist_test.py)](https://github.com/learnables/learn2learn/blob/a1da2c755856505556241809bba9b150f36850c2/tests/integration/meta_mnist_test.py#L119) that ensures that training on `meta_mnist` gives us better than random accuracy i.e 0.2.

**Comment by aGiant** [comment]
import learn2learn as l2l
print(l2l.__version__)

Result:
0.0.4.1

**Comment by seba-1511** [comment]
Closing, as it seems to work now.
