### ISSUE TITLE
Error during installation (UnicodeDecodeError)

### ISSUE THREAD

**Issue by Soo95** [learnables/learn2learn#87]
> Collecting learn2learn
>   Using cached https://files.pythonhosted.org/packages/9e/31/da004bafc94300b7d1d2c6da297c9064ae5bab8181e5d2eb02f669279d4b/learn2learn-0.0.5.tar.gz
>     ERROR: Command errored out with exit status 1:
>      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5xlmbvh1/learn2learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5xlmbvh1/learn2learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-5xlmbvh1/learn2learn/pip-egg-info
>          cwd: /tmp/pip-install-5xlmbvh1/learn2learn/
>     Complete output (7 lines):
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-install-5xlmbvh1/learn2learn/setup.py", line 26, in <module>
>         long_description=open('README.md').read(),
>       File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
>         return codecs.ascii_decode(input, self.errors)[0]
>     UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3190: ordinal not in range(128)
>     ----------------------------------------
> ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Hi, I wanted to install learn2learn by 'pip install learn2learn', but it's failed by this error.
I've searched how to solve this problem, and applied it, but it's also failed.
would you tell me how to solve this problem?

**Comment by seba-1511** [comment]
Thanks for the bug report. Out of curiosity, what was the thing you tried to solve this error ?

I suspect that it might be an issue with accented characters in the README, and so I've removed them in PR #86 .

**Comment by Soo95** [comment]
@seba-1511 
Thanks for reply! I may refer to https://github.com/pytorch/text/issues/77. 
Is there a way to install package via git?

**Comment by seba-1511** [comment]
Yes, you can try the following:

```shell
git clone https://github.com/learnables/learn2learn/
cd learn2learn
git checkout v0.5 # only if you want to include the patch
pip install -e .
```

**Comment by Soo95** [comment]
Thanks a lot :) It works

**Comment by petrapoklukar** [comment]
Hi, 

I am going to reuse this thread to report a similar issue. The solution you suggested didn't work either. I am getting the following error:

Collecting learn2learn
  Using cached learn2learn-0.1.3.tar.gz (548 kB)
Requirement already satisfied: numpy>=1.15.4 in ./anaconda3/lib/python3.7/site-packages (from learn2learn) (1.18.1)
Requirement already satisfied: gym>=0.14.0 in ./anaconda3/lib/python3.7/site-packages (from learn2learn) (0.17.2)
Requirement already satisfied: torch>=1.1.0 in ./anaconda3/lib/python3.7/site-packages (from learn2learn) (1.5.0)
Requirement already satisfied: torchvision>=0.3.0 in ./anaconda3/lib/python3.7/site-packages (from learn2learn) (0.6.0a0+82fd1c8)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.7/site-packages (from learn2learn) (1.0.1)
Requirement already satisfied: requests in ./anaconda3/lib/python3.7/site-packages (from learn2learn) (2.22.0)
Requirement already satisfied: pyglet<=1.5.0,>=1.4.0 in ./anaconda3/lib/python3.7/site-packages (from gym>=0.14.0->learn2learn) (1.5.0)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.7/site-packages (from gym>=0.14.0->learn2learn) (1.4.1)
Requirement already satisfied: cloudpickle<1.4.0,>=1.2.0 in ./anaconda3/lib/python3.7/site-packages (from gym>=0.14.0->learn2learn) (1.3.0)
Requirement already satisfied: future in ./anaconda3/lib/python3.7/site-packages (from torch>=1.1.0->learn2learn) (0.18.2)
Requirement already satisfied: pillow>=4.1.1 in ./anaconda3/lib/python3.7/site-packages (from torchvision>=0.3.0->learn2learn) (7.0.0)
Requirement already satisfied: python-dateutil>=2.6.1 in ./anaconda3/lib/python3.7/site-packages (from pandas->learn2learn) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/lib/python3.7/site-packages (from pandas->learn2learn) (2019.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in ./anaconda3/lib/python3.7/site-packages (from requests->learn2learn) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./anaconda3/lib/python3.7/site-packages (from requests->learn2learn) (1.25.8)
Requirement already satisfied: idna<2.9,>=2.5 in ./anaconda3/lib/python3.7/site-packages (from requests->learn2learn) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in ./anaconda3/lib/python3.7/site-packages (from requests->learn2learn) (2019.11.28)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->learn2learn) (1.14.0)
Building wheels for collected packages: learn2learn
  Building wheel for learn2learn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/petra/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8kjqviyk/learn2learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8kjqviyk/learn2learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-76kbz2df
       cwd: /tmp/pip-install-8kjqviyk/learn2learn/
  Complete output (120 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/tests
  copying tests/__init__.py -> build/lib.linux-x86_64-3.7/tests
  creating build/lib.linux-x86_64-3.7/learn2learn
  copying learn2learn/_version.py -> build/lib.linux-x86_64-3.7/learn2learn
  copying learn2learn/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn
  copying learn2learn/utils.py -> build/lib.linux-x86_64-3.7/learn2learn
  creating build/lib.linux-x86_64-3.7/tests/integration
  copying tests/integration/maml_miniimagenet_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/integration
  copying tests/integration/protonets_miniimagenet_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/integration
  copying tests/integration/__init__.py -> build/lib.linux-x86_64-3.7/tests/integration
  copying tests/integration/maml_omniglot_test.py -> build/lib.linux-x86_64-3.7/tests/integration
  creating build/lib.linux-x86_64-3.7/tests/unit
  copying tests/unit/utils_test.py -> build/lib.linux-x86_64-3.7/tests/unit
  copying tests/unit/__init__.py -> build/lib.linux-x86_64-3.7/tests/unit
  creating build/lib.linux-x86_64-3.7/tests/unit/vision
  copying tests/unit/vision/fc100_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
  copying tests/unit/vision/cifarfs_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
  copying tests/unit/vision/cu_birds200_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
  copying tests/unit/vision/vgg_flowers_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
  copying tests/unit/vision/fgvc_aircraft_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
  copying tests/unit/vision/__init__.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
  copying tests/unit/vision/benchmarks_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
  copying tests/unit/vision/tiered_imagenet_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
  creating build/lib.linux-x86_64-3.7/tests/unit/data
  copying tests/unit/data/transforms_test.py -> build/lib.linux-x86_64-3.7/tests/unit/data
  copying tests/unit/data/util_datasets.py -> build/lib.linux-x86_64-3.7/tests/unit/data
  copying tests/unit/data/__init__.py -> build/lib.linux-x86_64-3.7/tests/unit/data
  copying tests/unit/data/metadataset_test.py -> build/lib.linux-x86_64-3.7/tests/unit/data
  copying tests/unit/data/task_dataset_test.py -> build/lib.linux-x86_64-3.7/tests/unit/data
  creating build/lib.linux-x86_64-3.7/tests/unit/algorithms
  copying tests/unit/algorithms/metasgd_test.py -> build/lib.linux-x86_64-3.7/tests/unit/algorithms
  copying tests/unit/algorithms/__init__.py -> build/lib.linux-x86_64-3.7/tests/unit/algorithms
  copying tests/unit/algorithms/maml_test.py -> build/lib.linux-x86_64-3.7/tests/unit/algorithms
  copying tests/unit/algorithms/gbml_test.py -> build/lib.linux-x86_64-3.7/tests/unit/algorithms
  creating build/lib.linux-x86_64-3.7/learn2learn/nn
  copying learn2learn/nn/kroneckers.py -> build/lib.linux-x86_64-3.7/learn2learn/nn
  copying learn2learn/nn/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/nn
  copying learn2learn/nn/misc.py -> build/lib.linux-x86_64-3.7/learn2learn/nn
  creating build/lib.linux-x86_64-3.7/learn2learn/vision
  copying learn2learn/vision/transforms.py -> build/lib.linux-x86_64-3.7/learn2learn/vision
  copying learn2learn/vision/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/vision
  copying learn2learn/vision/models.py -> build/lib.linux-x86_64-3.7/learn2learn/vision
  creating build/lib.linux-x86_64-3.7/learn2learn/text
  copying learn2learn/text/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/text
  creating build/lib.linux-x86_64-3.7/learn2learn/optim
  copying learn2learn/optim/learnable_optimizer.py -> build/lib.linux-x86_64-3.7/learn2learn/optim
  copying learn2learn/optim/parameter_update.py -> build/lib.linux-x86_64-3.7/learn2learn/optim
  copying learn2learn/optim/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/optim
  creating build/lib.linux-x86_64-3.7/learn2learn/gym
  copying learn2learn/gym/async_vec_env.py -> build/lib.linux-x86_64-3.7/learn2learn/gym
  copying learn2learn/gym/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym
  creating build/lib.linux-x86_64-3.7/learn2learn/data
  copying learn2learn/data/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/data
  copying learn2learn/data/utils.py -> build/lib.linux-x86_64-3.7/learn2learn/data
  creating build/lib.linux-x86_64-3.7/learn2learn/algorithms
  copying learn2learn/algorithms/maml.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
  copying learn2learn/algorithms/base_learner.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
  copying learn2learn/algorithms/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
  copying learn2learn/algorithms/meta_sgd.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
  copying learn2learn/algorithms/gbml.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
  creating build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
  copying learn2learn/vision/benchmarks/fc100_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
  copying learn2learn/vision/benchmarks/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
  copying learn2learn/vision/benchmarks/mini_imagenet_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
  copying learn2learn/vision/benchmarks/cifarfs_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
  copying learn2learn/vision/benchmarks/tiered_imagenet_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
  copying learn2learn/vision/benchmarks/omniglot_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
  creating build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  copying learn2learn/vision/datasets/tiered_imagenet.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  copying learn2learn/vision/datasets/vgg_flowers.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  copying learn2learn/vision/datasets/fc100.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  copying learn2learn/vision/datasets/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  copying learn2learn/vision/datasets/full_omniglot.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  copying learn2learn/vision/datasets/cu_birds200.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  copying learn2learn/vision/datasets/fgvc_aircraft.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  copying learn2learn/vision/datasets/cifarfs.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  copying learn2learn/vision/datasets/mini_imagenet.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
  creating build/lib.linux-x86_64-3.7/learn2learn/text/datasets
  copying learn2learn/text/datasets/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/text/datasets
  copying learn2learn/text/datasets/news_classification.py -> build/lib.linux-x86_64-3.7/learn2learn/text/datasets
  creating build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
  copying learn2learn/optim/transforms/module_transform.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
  copying learn2learn/optim/transforms/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
  copying learn2learn/optim/transforms/transform_dictionary.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
  copying learn2learn/optim/transforms/kronecker_transform.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
  copying learn2learn/optim/transforms/metacurvature_transform.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
  creating build/lib.linux-x86_64-3.7/learn2learn/optim/update_rules
  copying learn2learn/optim/update_rules/differentiable_sgd.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/update_rules
  copying learn2learn/optim/update_rules/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/update_rules
  creating build/lib.linux-x86_64-3.7/learn2learn/gym/envs
  copying learn2learn/gym/envs/subproc_vec_env.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs
  copying learn2learn/gym/envs/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs
  copying learn2learn/gym/envs/meta_env.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs
  creating build/lib.linux-x86_64-3.7/learn2learn/gym/envs/particles
  copying learn2learn/gym/envs/particles/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/particles
  copying learn2learn/gym/envs/particles/particles_2d.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/particles
  creating build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
  copying learn2learn/gym/envs/mujoco/humanoid_direction.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
  copying learn2learn/gym/envs/mujoco/humanoid_forward_backward.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
  copying learn2learn/gym/envs/mujoco/dummy_mujoco_env.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
  copying learn2learn/gym/envs/mujoco/ant_direction.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
  copying learn2learn/gym/envs/mujoco/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
  copying learn2learn/gym/envs/mujoco/ant_forward_backward.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
  copying learn2learn/gym/envs/mujoco/halfcheetah_forward_backward.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
  creating build/lib.linux-x86_64-3.7/learn2learn/gym/envs/metaworld
  copying learn2learn/gym/envs/metaworld/metaworld.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/metaworld
  copying learn2learn/gym/envs/metaworld/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/metaworld
  running build_ext
  building 'learn2learn.data.meta_dataset' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/learn2learn
  creating build/temp.linux-x86_64-3.7/learn2learn/data
  gcc -pthread -B /home/petra/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/petra/anaconda3/include/python3.7m -c learn2learn/data/meta_dataset.c -o build/temp.linux-x86_64-3.7/learn2learn/data/meta_dataset.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for learn2learn
  Running setup.py clean for learn2learn
Failed to build learn2learn
Installing collected packages: learn2learn
    Running setup.py install for learn2learn ... error
    ERROR: Command errored out with exit status 1:
     command: /home/petra/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8kjqviyk/learn2learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8kjqviyk/learn2learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pxc6rb7a/install-record.txt --single-version-externally-managed --compile --install-headers /home/petra/anaconda3/include/python3.7m/learn2learn
         cwd: /tmp/pip-install-8kjqviyk/learn2learn/
    Complete output (120 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/tests
    copying tests/__init__.py -> build/lib.linux-x86_64-3.7/tests
    creating build/lib.linux-x86_64-3.7/learn2learn
    copying learn2learn/_version.py -> build/lib.linux-x86_64-3.7/learn2learn
    copying learn2learn/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn
    copying learn2learn/utils.py -> build/lib.linux-x86_64-3.7/learn2learn
    creating build/lib.linux-x86_64-3.7/tests/integration
    copying tests/integration/maml_miniimagenet_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/integration
    copying tests/integration/protonets_miniimagenet_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/integration
    copying tests/integration/__init__.py -> build/lib.linux-x86_64-3.7/tests/integration
    copying tests/integration/maml_omniglot_test.py -> build/lib.linux-x86_64-3.7/tests/integration
    creating build/lib.linux-x86_64-3.7/tests/unit
    copying tests/unit/utils_test.py -> build/lib.linux-x86_64-3.7/tests/unit
    copying tests/unit/__init__.py -> build/lib.linux-x86_64-3.7/tests/unit
    creating build/lib.linux-x86_64-3.7/tests/unit/vision
    copying tests/unit/vision/fc100_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
    copying tests/unit/vision/cifarfs_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
    copying tests/unit/vision/cu_birds200_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
    copying tests/unit/vision/vgg_flowers_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
    copying tests/unit/vision/fgvc_aircraft_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
    copying tests/unit/vision/__init__.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
    copying tests/unit/vision/benchmarks_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
    copying tests/unit/vision/tiered_imagenet_test_notravis.py -> build/lib.linux-x86_64-3.7/tests/unit/vision
    creating build/lib.linux-x86_64-3.7/tests/unit/data
    copying tests/unit/data/transforms_test.py -> build/lib.linux-x86_64-3.7/tests/unit/data
    copying tests/unit/data/util_datasets.py -> build/lib.linux-x86_64-3.7/tests/unit/data
    copying tests/unit/data/__init__.py -> build/lib.linux-x86_64-3.7/tests/unit/data
    copying tests/unit/data/metadataset_test.py -> build/lib.linux-x86_64-3.7/tests/unit/data
    copying tests/unit/data/task_dataset_test.py -> build/lib.linux-x86_64-3.7/tests/unit/data
    creating build/lib.linux-x86_64-3.7/tests/unit/algorithms
    copying tests/unit/algorithms/metasgd_test.py -> build/lib.linux-x86_64-3.7/tests/unit/algorithms
    copying tests/unit/algorithms/__init__.py -> build/lib.linux-x86_64-3.7/tests/unit/algorithms
    copying tests/unit/algorithms/maml_test.py -> build/lib.linux-x86_64-3.7/tests/unit/algorithms
    copying tests/unit/algorithms/gbml_test.py -> build/lib.linux-x86_64-3.7/tests/unit/algorithms
    creating build/lib.linux-x86_64-3.7/learn2learn/nn
    copying learn2learn/nn/kroneckers.py -> build/lib.linux-x86_64-3.7/learn2learn/nn
    copying learn2learn/nn/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/nn
    copying learn2learn/nn/misc.py -> build/lib.linux-x86_64-3.7/learn2learn/nn
    creating build/lib.linux-x86_64-3.7/learn2learn/vision
    copying learn2learn/vision/transforms.py -> build/lib.linux-x86_64-3.7/learn2learn/vision
    copying learn2learn/vision/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/vision
    copying learn2learn/vision/models.py -> build/lib.linux-x86_64-3.7/learn2learn/vision
    creating build/lib.linux-x86_64-3.7/learn2learn/text
    copying learn2learn/text/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/text
    creating build/lib.linux-x86_64-3.7/learn2learn/optim
    copying learn2learn/optim/learnable_optimizer.py -> build/lib.linux-x86_64-3.7/learn2learn/optim
    copying learn2learn/optim/parameter_update.py -> build/lib.linux-x86_64-3.7/learn2learn/optim
    copying learn2learn/optim/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/optim
    creating build/lib.linux-x86_64-3.7/learn2learn/gym
    copying learn2learn/gym/async_vec_env.py -> build/lib.linux-x86_64-3.7/learn2learn/gym
    copying learn2learn/gym/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym
    creating build/lib.linux-x86_64-3.7/learn2learn/data
    copying learn2learn/data/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/data
    copying learn2learn/data/utils.py -> build/lib.linux-x86_64-3.7/learn2learn/data
    creating build/lib.linux-x86_64-3.7/learn2learn/algorithms
    copying learn2learn/algorithms/maml.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
    copying learn2learn/algorithms/base_learner.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
    copying learn2learn/algorithms/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
    copying learn2learn/algorithms/meta_sgd.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
    copying learn2learn/algorithms/gbml.py -> build/lib.linux-x86_64-3.7/learn2learn/algorithms
    creating build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
    copying learn2learn/vision/benchmarks/fc100_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
    copying learn2learn/vision/benchmarks/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
    copying learn2learn/vision/benchmarks/mini_imagenet_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
    copying learn2learn/vision/benchmarks/cifarfs_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
    copying learn2learn/vision/benchmarks/tiered_imagenet_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
    copying learn2learn/vision/benchmarks/omniglot_benchmark.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/benchmarks
    creating build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    copying learn2learn/vision/datasets/tiered_imagenet.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    copying learn2learn/vision/datasets/vgg_flowers.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    copying learn2learn/vision/datasets/fc100.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    copying learn2learn/vision/datasets/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    copying learn2learn/vision/datasets/full_omniglot.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    copying learn2learn/vision/datasets/cu_birds200.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    copying learn2learn/vision/datasets/fgvc_aircraft.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    copying learn2learn/vision/datasets/cifarfs.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    copying learn2learn/vision/datasets/mini_imagenet.py -> build/lib.linux-x86_64-3.7/learn2learn/vision/datasets
    creating build/lib.linux-x86_64-3.7/learn2learn/text/datasets
    copying learn2learn/text/datasets/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/text/datasets
    copying learn2learn/text/datasets/news_classification.py -> build/lib.linux-x86_64-3.7/learn2learn/text/datasets
    creating build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
    copying learn2learn/optim/transforms/module_transform.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
    copying learn2learn/optim/transforms/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
    copying learn2learn/optim/transforms/transform_dictionary.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
    copying learn2learn/optim/transforms/kronecker_transform.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
    copying learn2learn/optim/transforms/metacurvature_transform.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/transforms
    creating build/lib.linux-x86_64-3.7/learn2learn/optim/update_rules
    copying learn2learn/optim/update_rules/differentiable_sgd.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/update_rules
    copying learn2learn/optim/update_rules/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/optim/update_rules
    creating build/lib.linux-x86_64-3.7/learn2learn/gym/envs
    copying learn2learn/gym/envs/subproc_vec_env.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs
    copying learn2learn/gym/envs/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs
    copying learn2learn/gym/envs/meta_env.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs
    creating build/lib.linux-x86_64-3.7/learn2learn/gym/envs/particles
    copying learn2learn/gym/envs/particles/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/particles
    copying learn2learn/gym/envs/particles/particles_2d.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/particles
    creating build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
    copying learn2learn/gym/envs/mujoco/humanoid_direction.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
    copying learn2learn/gym/envs/mujoco/humanoid_forward_backward.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
    copying learn2learn/gym/envs/mujoco/dummy_mujoco_env.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
    copying learn2learn/gym/envs/mujoco/ant_direction.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
    copying learn2learn/gym/envs/mujoco/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
    copying learn2learn/gym/envs/mujoco/ant_forward_backward.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
    copying learn2learn/gym/envs/mujoco/halfcheetah_forward_backward.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/mujoco
    creating build/lib.linux-x86_64-3.7/learn2learn/gym/envs/metaworld
    copying learn2learn/gym/envs/metaworld/metaworld.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/metaworld
    copying learn2learn/gym/envs/metaworld/__init__.py -> build/lib.linux-x86_64-3.7/learn2learn/gym/envs/metaworld
    running build_ext
    building 'learn2learn.data.meta_dataset' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/learn2learn
    creating build/temp.linux-x86_64-3.7/learn2learn/data
    gcc -pthread -B /home/petra/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/petra/anaconda3/include/python3.7m -c learn2learn/data/meta_dataset.c -o build/temp.linux-x86_64-3.7/learn2learn/data/meta_dataset.o
    unable to execute 'gcc': No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/petra/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8kjqviyk/learn2learn/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8kjqviyk/learn2learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pxc6rb7a/install-record.txt --single-version-externally-managed --compile --install-headers /home/petra/anaconda3/include/python3.7m/learn2learn Check the logs for full command output.


If you can help me with the installation, that would be great!

Petra

**Comment by seba-1511** [comment]
Hello @petrapoklukar ,

What's the version of GCC you have installed? And could you check if you're able to install Cython on your machine?

**Comment by petrapoklukar** [comment]
Hi, 

thanks for pointing this out, GCC wasn't installed and now pip installation went through so it works!

Petra
