### ISSUE TITLE
AttributeError: module 'learn2learn.text.datasets' has no attribute 'TaskGenerator'

### ISSUE THREAD

**Issue by casijoe5231** [learnables/learn2learn#96]
Hi,

I am trying to run the news_topic_classification.py in the text examples folder, but I keep running into the error mentioned here:

`Traceback (most recent call last):
  File "news_topic_classification.py", line 166, in <module>
    download_location=args.download_location)
  File "news_topic_classification.py", line 84, in main
    train_gen = l2l.text.datasets.TaskGenerator(text_train, ways=ways)
AttributeError: module 'learn2learn.text.datasets' has no attribute 'TaskGenerator'`

 I am using a conda venv with the following pip list:

![image](https://user-images.githubusercontent.com/30308873/71574767-3791e200-2b10-11ea-9c16-25452bf7da1b.png)

**Comment by lightningbaby** [comment]
I meet the same problem.

**Comment by seba-1511** [comment]
Thanks for the feedback. It appears that the text example hasn't been ported to use the new `TaskDataset`. This should be fairly straightforward; an example of such port is [available for the mini-ImageNet example](https://github.com/learnables/learn2learn/pull/90/files#diff-e62590ec8ca5ec83c309524a57cfc749).

One word of caution: we were never able to get MAML to work well for text. 

cc: @debajyotidatta who contributed the example.
